---
title: "Trump Trade War Diary — Day 46"
description: "Duties imposed to address the flow of illicit drugs across our borders are now: - 25% tariffs on goods that do not satisfy U.S.-Mexico-Canada Agreement (USMCA) rules of origin."
date: "2025-03-07"
categories: [trade-wars, trump-trade-war-diary]
---

Now the updated version of "fetanyl" tariffs is available on the White House website: [link](https://www.whitehouse.gov/fact-sheets/2025/03/fact-sheet-president-donald-j-trump-adjusts-tariffs-on-canada-and-mexico-to-minimize-disruption-to-the-automotive-industry/)


Duties imposed to address the flow of illicit drugs across our borders are now:
- 25% tariffs on goods that do not satisfy U.S.-Mexico-Canada Agreement (USMCA) rules of origin.
- A lower 10% tariff on those energy products imported from Canada that fall outside the USMCA preference.
- A lower 10% tariff on any potash imported from Canada and Mexico that falls outside the USMCA preference.
- No tariffs on those goods from Canada and Mexico that claim and qualify for USMCA preference.

Suddenly potash appeared on the list. Its import from Canada (HS2815) in 2024 was about 30 mln USD, so the inclusion in the list was requested by some very specific group of people. Will be interesting to look at who those people are. Expect the list to grow in the coming days, as more and more industries will be affected by the tariffs.
