<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2025-04-11">
<meta name="description" content="Recent developments in the trade relationship between the United States and China concerning tariffs within the last 10 days have been marked by continued tension, particularly with the US maintaining and escalating tariff pressure on China while adopting a…">

<title>Trump Trade War Diary — Days 81–100 – Oleksandr Shepotylo</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../images/favicon.png" rel="icon" type="image/png">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-bb62276ab45c84d9efd712f51ff97b5a.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-6d202d7af2714ce3a045046f87859a38.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="../../site_libs/quarto-contrib/iconify-3.0.0/iconify-icon.min.js"></script>
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Oleksandr Shepotylo</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-research" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Research</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-research">    
        <li>
    <a class="dropdown-item" href="../../research/index.html">
 <span class="dropdown-text">All research</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li>
    <a class="dropdown-item" href="../../brexit/index.html">
 <span class="dropdown-text">Brexit</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../trade-wars/index.html">
 <span class="dropdown-text">Trade Wars</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ukraine/index.html">
 <span class="dropdown-text">Ukraine</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../firms/index.html">
 <span class="dropdown-text">Firms</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../other/index.html">
 <span class="dropdown-text">Other</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../../consultancy/index.html"> 
<span class="menu-text">Consultancy</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../blog.html"> 
<span class="menu-text">Blog</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../cv.pdf"> 
<span class="menu-text">CV</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/oshepotylo"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/oleksandr-shepotylo-b050353/"> <i class="bi bi-linkedin" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://bsky.app/profile/shepotylo"> 
<span class="menu-text"><iconify-icon role="img" inline="" icon="simple-icons:bluesky" aria-label="Icon bluesky from simple-icons Iconify.design set." title="Icon bluesky from simple-icons Iconify.design set."></iconify-icon></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://oleksandrshepotylo.substack.com/"> 
<span class="menu-text"><iconify-icon role="img" inline="" icon="simple-icons:substack" aria-label="Icon substack from simple-icons Iconify.design set." title="Icon substack from simple-icons Iconify.design set."></iconify-icon></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://orcid.org/0000-0003-4990-6025"> 
<span class="menu-text"><iconify-icon role="img" inline="" icon="academicons:orcid" aria-label="Icon orcid from academicons Iconify.design set." title="Icon orcid from academicons Iconify.design set."></iconify-icon></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="../../blog.xml"> <i class="bi bi-rss" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#us-china-trade-war-escalation" id="toc-us-china-trade-war-escalation" class="nav-link active" data-scroll-target="#us-china-trade-war-escalation">US-China Trade War Escalation</a></li>
  <li><a href="#recent-developments-in-us-tariffs-against-china-and-chinas-responses-april-17th-to-april-27th-2025" id="toc-recent-developments-in-us-tariffs-against-china-and-chinas-responses-april-17th-to-april-27th-2025" class="nav-link" data-scroll-target="#recent-developments-in-us-tariffs-against-china-and-chinas-responses-april-17th-to-april-27th-2025"><strong>Recent Developments in US Tariffs Against China and China’s Responses (April 17th to April 27th, 2025)</strong></a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Trump Trade War Diary — Days 81–100</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
  <div class="quarto-categories">
    <div class="quarto-category">trade-wars</div>
    <div class="quarto-category">trump-trade-war-diary</div>
  </div>
  </div>

<div>
  <div class="description">
    Recent developments in the trade relationship between the United States and China concerning tariffs within the last 10 days have been marked by continued tension, particularly with the US maintaining and escalating tariff pressure on China while adopting a…
  </div>
</div>


<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">April 11, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="us-china-trade-war-escalation" class="level2">
<h2 class="anchored" data-anchor-id="us-china-trade-war-escalation">US-China Trade War Escalation</h2>
</section>
<section id="recent-developments-in-us-tariffs-against-china-and-chinas-responses-april-17th-to-april-27th-2025" class="level1">
<h1><strong>Recent Developments in US Tariffs Against China and China’s Responses (April 17th to April 27th, 2025)</strong></h1>
<p><strong>1. Executive Summary</strong></p>
<p>Recent developments in the trade relationship between the United States and China concerning tariffs within the last 10 days have been marked by continued tension, particularly with the US maintaining and escalating tariff pressure on China while adopting a temporary pause with most other trading partners. Key US policy changes during this period, building on earlier actions, include the maintenance of significantly elevated tariff rates on Chinese imports and the formal announcement of the elimination of the “de minimis” exemption for low-value goods from China and Hong Kong. In response, China has reiterated its strong opposition through the release of a comprehensive White Paper on US trade, continued to deny US claims of ongoing tariff negotiations, and indicated a potential consideration of targeted tariff exemptions on certain essential US goods. The overarching trend suggests a persistent and deepening trade conflict between the two economic giants, carrying significant implications for global trade, economic stability, and geopolitical relations.</p>
<p><strong>2. Background: Trump’s Tariff Policy Against China (Pre-Last 10 Days)</strong></p>
<p>The imposition of tariffs by the United States on goods imported from China has been a defining feature of trade policy under President Trump, originating from stated objectives such as addressing substantial trade deficits and combating the alleged theft of US intellectual property.1 The initial major step in this direction occurred in 2018 with the implementation of tariffs under Section 301 of the Trade Act of 1974, targeting a wide array of Chinese products, including electronics, machinery, and consumer goods.2 Over time, the scope and rates of these tariffs expanded, affecting sectors like steel, aluminum, and, more recently, automobiles.3 Prior to the 10-day period under review, the year 2025 had already witnessed significant increases in tariffs on Chinese imports. Notably, on April 2, 2025, President Trump announced what was termed “Liberation Day,” a significant escalation involving a baseline tariff of 10% on almost all imports and higher “reciprocal tariffs” levied on specific countries based on their trade balances with the US.3 This announcement included a substantial initial increase in tariffs on goods originating from China, setting the stage for the developments observed within the subsequent 10 days.</p>
<p><strong>3. US Policy Changes on China Tariffs in the Last 10 Days (From approximately April 17th to April 27th, 2025)</strong></p>
<p><strong>3.1. Initial High Tariffs and Subsequent Pause</strong></p>
<p>The implementation of the “reciprocal tariffs” on April 9th marked a significant point in the ongoing trade dispute. This included an initial tariff of 34% on Chinese imports, which, when added to existing levies such as the 20% tariff related to fentanyl trafficking and earlier increases, brought the total tariff rate on many Chinese goods to 104%.4 However, on the very same day, the Trump administration announced a 90-day pause on these newly implemented reciprocal tariffs for the majority of countries.3 Critically, China was explicitly excluded from this temporary reprieve, signaling a clear and targeted intensification of the trade confrontation with Beijing.3 Coinciding with the announcement of the pause for other nations, the US administration further escalated the trade war with China by increasing the tariff rate on Chinese imports to 125%.5 This rapid sequence of policy changes underscored a strategic decision to single out China for heightened tariff pressure. Subsequently, on April 10th, the White House clarified that the cumulative tariff burden on goods imported from China had reached an unprecedented 145%, highlighting the severity of the trade measures specifically targeting Beijing.5</p>
<p><strong>3.2. De Minimis Exemption Closure</strong></p>
<p>Within the 10-day period, the US administration formally announced the decision to eliminate the “de minimis” exemption for low-value imports originating from China and Hong Kong, with the policy set to take effect on May 2, 2025.4 This policy change entails a significant increase in duties applied to postal items valued at or under $800 arriving from mainland China and Hong Kong. These duties were set to reach as high as 120% of the item’s value or a specific duty of $100 per item initially, with further increases to $200 per item planned for June 1, 2025.11 The Trump administration explicitly linked this policy decision to its stated objective of combating China’s perceived role in the ongoing synthetic opioid crisis in the United States, asserting that deceptive shipping practices were being exploited through the de minimis exemption.22 This action demonstrates a more targeted approach in the US trade strategy towards China, extending beyond broad tariff increases to address specific concerns related to illicit goods flows.</p>
<p><strong>3.3. Rhetoric and Signals Regarding Future Actions</strong></p>
<p>Throughout the last 10 days, statements from US officials provided insights into the administration’s thinking regarding the trade war with China. Treasury Secretary Scott Bessent, in remarks likely made just before or at the beginning of this period, described the ongoing tariff showdown against China as “unsustainable,” suggesting a potential for de-escalation in the future.20 Similarly, President Trump indicated that the final tariff rate applied to China would eventually be reduced “substantially” from the current peak of 145%, offering a glimpse of a possible long-term scenario, although no immediate policy changes reflecting this sentiment were implemented within the timeframe.20 However, towards the end of the 10-day window (as indicated by reports from April 28th, slightly outside the strict timeframe but indicative of ongoing sentiment), President Trump expressed skepticism about implementing another pause on tariffs and reiterated his demand for concessions from China, suggesting a continued stance of pressure.25 Furthermore, the possibility of imposing additional tariffs targeting specific strategic sectors, such as semiconductors and pharmaceuticals, remained under consideration, as reported earlier in April.4 These various signals suggest a complex and potentially evolving US strategy, balancing an acknowledgment of the long-term unsustainability of the current high tariffs with a continued commitment to using them as leverage to achieve trade concessions from China.</p>
<p><strong>4. China’s Response to US Tariff Actions in the Last 10 Days</strong></p>
<p><strong>4.1. Immediate Retaliation and Strong Rhetoric</strong></p>
<p>In direct response to the US implementation of “reciprocal tariffs,” China announced on April 9th that it would raise its tariffs on US goods to 84%, effective from April 10th.5 This move to match the initial US reciprocal tariff rate demonstrated China’s unwavering policy of retaliating in kind to US tariff actions. China’s Ministry of Finance issued a strong condemnation of the US escalation, characterizing it as a “mistake on top of a mistake,” clearly signaling Beijing’s firm opposition to the US tariff policy.14 Furthermore, Chinese authorities reiterated their resolute stance against the US tariffs, vowing to “fight to the end” and underscoring their determination to withstand the pressure and their readiness to implement further countermeasures if necessary.6</p>
<p><strong>4.2. China’s White Paper on US Trade</strong></p>
<p>A significant aspect of China’s response at the beginning of the 10-day period was the release of a comprehensive White Paper on April 9th, formally titled “China’s Position on Some Issues Concerning China-US Economic and Trade Relations”.8 This document provided a detailed articulation of China’s official perspective on its economic and trade relationship with the United States. Key arguments presented in the White Paper included an emphasis on the mutually beneficial nature of bilateral trade, assertions of China’s adherence to the 2020 trade agreement, and strong criticisms of what China views as US unilateralism and protectionist trade practices.29 The White Paper also explicitly called for the resolution of trade disputes through dialogue and cooperation based on principles of equality and mutual benefit, outlining China’s preferred approach to de-escalating the ongoing conflict.29 The release of this document served as a formal and comprehensive diplomatic response to the escalating trade tensions.</p>
<p><strong>4.3. Repeated Denial of Ongoing Tariff Negotiations</strong></p>
<p>Throughout the last 10 days, China consistently and firmly denied claims made by the US administration suggesting that active tariff negotiations were taking place between the two nations.18 The Chinese Embassy in Washington issued a direct and unambiguous statement via social media, explicitly asserting that “China and the US are NOT having any consultation or negotiation on #tariffs” and urging the US to refrain from creating confusion on this matter.38 Further reinforcing this stance, a spokesperson for China’s Ministry of Commerce dismissed US claims of progress in negotiations as “groundless” and lacking any “factual basis”.42 This consistent denial highlights a significant divergence in the narratives presented by the two countries regarding the status of their trade relationship.</p>
<p><strong>4.4. Consideration of Tariff Exemptions on Some US Goods</strong></p>
<p>Towards the end of the 10-day period, reports emerged indicating that China was actively considering exempting certain US imports from its retaliatory tariffs.18 These potential exemptions reportedly included essential items such as medical equipment, specific industrial chemicals like ethane, aircraft leasing payments, and a selection of semiconductor products, although not memory chips.18 This consideration is likely driven by growing concerns within China about the adverse impact of the ongoing trade war on its own critical industries and the potential for disruptions to vital supply chains that rely on specific US-made components or materials.39 The Chinese government has reportedly been soliciting input from local companies to identify specific US imports for which tariff relief would be most beneficial, suggesting a targeted and pragmatic approach to mitigating the domestic economic fallout.39 This potential move indicates a nuanced approach by China, balancing its firm stance against US tariffs with a recognition of the need to protect its own economic interests.</p>
<p><strong>4.5. Strong Warning Against Trade Deals at China’s Expense</strong></p>
<p>China reiterated its strong warning to other countries against entering into trade agreements with the United States that could potentially undermine or negatively impact China’s economic interests.20 The Commerce Ministry explicitly stated, “China firmly opposes any party reaching a deal at the expense of China’s interests,” underscoring Beijing’s determination to protect its position in the global trade landscape.20 This stance reflects China’s broader strategic concerns extending beyond its direct trade relationship with the US, indicating its efforts to prevent the US from forming alliances or striking deals that could isolate or disadvantage China in the international trade arena.</p>
<p><strong>4.6. Continued Potential for Further Retaliation and Use of Export Controls</strong></p>
<p>The potential for China to implement further retaliatory measures, including the use of export controls, remains a significant factor in the ongoing trade dispute.3 Specifically, China possesses leverage through its dominance in the production of rare earth minerals, which are critical for various high-tech industries globally. The existing practice of China adding US firms to lists subject to export controls and trade sanctions demonstrates its willingness to employ non-tariff measures in response to US actions.5 These potential actions highlight the multifaceted nature of China’s response capabilities beyond just the imposition of tariffs.</p>
<p><strong>5. Analysis and Implications</strong></p>
<p><strong>5.1. Intensifying Economic Impact on Both Countries</strong></p>
<p>The sustained high levels of tariffs imposed by both the United States and China are likely to have an increasingly negative impact on their respective economies. For US businesses and consumers, the escalating tariffs translate to higher import costs and, consequently, increased prices for a wide range of goods, potentially leading to inflationary pressures.1 Supply chains, particularly those heavily reliant on Chinese imports, face disruptions, potentially affecting production and availability of goods.1 On the other side, Chinese manufacturers and exporters are facing significant challenges due to the drastically reduced access to the crucial US market, a direct consequence of the 145% tariff rate on many of their goods.2 This is further compounded by the impact of China’s own retaliatory tariffs on US goods, affecting US exporters as well.2 International organizations, such as the International Monetary Fund, and numerous economic analysts have expressed growing concerns that these escalating tariffs could fuel inflation in both the US and China, and contribute to a broader slowdown in the global economy, underscoring the interconnected nature of international trade.4</p>
<p><strong>5.2. Accelerating Reshaping of Global Supply Chains</strong></p>
<p>The sustained high levels of tariffs and the uncertainty surrounding the future of US-China trade policy are likely to further accelerate the ongoing trend of businesses re-evaluating and restructuring their global supply chains. Faced with tariffs as high as 145%, some Chinese firms are exploring the possibility of establishing manufacturing facilities within the United States or in other countries that are not subject to these tariffs, aiming to circumvent the punitive duties.1 Simultaneously, US companies that have historically relied on China for sourcing goods are increasingly seeking to diversify their supply chains, looking for alternative suppliers in other nations to mitigate the impact of the tariffs.1 These shifts in sourcing and production are likely to have significant long-term consequences, potentially leading to increased costs for consumers as supply chains are reconfigured, the emergence of new regional trade hubs, and a fundamental reshaping of the global trade patterns that have been established over several decades.1</p>
<p><strong>5.3. Deepening Geopolitical Tensions and Strategic Competition</strong></p>
<p>The ongoing trade war is not occurring in isolation; it is a significant factor contributing to the further deterioration of the broader relationship between the United States and China. The escalating tariffs and the accompanying rhetoric are exacerbating existing geopolitical tensions and potentially pushing the two nations towards a more confrontational stance, reminiscent of a “cold war” dynamic.2 This competition extends beyond trade into critical areas such as technology, security, and international diplomacy.2 In response, China is strategically seeking to strengthen its trade and diplomatic ties with other regions around the world, positioning itself as a proponent of multilateralism and increasingly criticizing the US approach to international trade and global governance as unilateral and protectionist.2 The trade war, therefore, is not just an economic dispute but an integral part of a larger strategic competition with far-reaching geopolitical implications.</p>
<p><strong>6. Conclusion</strong></p>
<p>In the last 10 days, US policy on tariffs against China has remained firmly in an escalatory mode, characterized by the maintenance of a 145% tariff rate on many Chinese goods and the notable exclusion of China from the 90-day pause on reciprocal tariffs granted to most other trading partners. Additionally, the US announced the impending closure of the de minimis exemption for low-value imports from China and Hong Kong, signaling a further tightening of trade restrictions. China’s response during this period has been multifaceted, including an immediate retaliatory tariff increase to 84% on US goods, a comprehensive diplomatic offensive through the release of a White Paper outlining its position on the trade dispute, and consistent denials of US claims regarding ongoing tariff negotiations. Notably, there were also reports suggesting that China is considering targeted tariff exemptions on certain essential US goods, indicating a potential pragmatic approach to mitigating the domestic economic impact of the trade war. Despite these nuanced considerations, the overall trajectory of US-China trade relations remains fraught with tension and uncertainty. The conflicting signals emanating from both sides regarding the potential for de-escalation versus continued confrontation underscore the fluidity of the situation. The possibility of further tariff increases by the US or additional retaliatory measures from China cannot be discounted. Looking ahead, the US-China trade relationship appears poised to remain contentious, with significant potential for negative repercussions on the global economy, the stability of international supply chains, and the broader geopolitical landscape.</p>
<p><strong>7. Potential Key Tables for the Report:</strong></p>
<p><strong>Table 1: Timeline of Key US-China Tariff Actions (April 9th - April 27th, 2025)</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Date</th>
<th style="text-align: left;">US Action</th>
<th style="text-align: left;">China’s Response</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">April 9th</td>
<td style="text-align: left;">Implementation of 34% Reciprocal Tariff on China, increasing total tariff to 104%</td>
<td style="text-align: left;">Announced retaliatory tariff increase to 84% on US goods, effective April 10th</td>
</tr>
<tr class="even">
<td style="text-align: left;">April 9th</td>
<td style="text-align: left;">Announcement of 90-day pause on Reciprocal Tariffs for most countries, excluding China</td>
<td style="text-align: left;">Released White Paper on US Trade outlining its position and calling for dialogue</td>
</tr>
<tr class="odd">
<td style="text-align: left;">April 9th</td>
<td style="text-align: left;">Increased tariff on China to 125%</td>
<td style="text-align: left;">Continued to deny US claims of ongoing tariff negotiations</td>
</tr>
<tr class="even">
<td style="text-align: left;">April 10th</td>
<td style="text-align: left;">White House clarified total tariff rate on Chinese imports reached 145%</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Approx. April 25th</td>
<td style="text-align: left;">Announcement (or increased prominence of earlier announcement) of De Minimis Exemption Closure for China and Hong Kong (effective May 2nd)</td>
<td style="text-align: left;">Reports emerged suggesting consideration of targeted tariff exemptions on some essential US goods (medical equipment, some chemicals, etc.)</td>
</tr>
</tbody>
</table>
<p><strong>Table 2: Summary of Current US Tariffs on Goods from China (As of April 27th, 2025)</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Tariff Type</th>
<th style="text-align: left;">Estimated Total Rate</th>
<th style="text-align: left;">Examples of Goods Affected</th>
<th style="text-align: left;">Effective Date</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Section 301 Tariffs (various tranches)</td>
<td style="text-align: left;">7.5% to 100% (depending on the product)</td>
<td style="text-align: left;">Electronics, machinery, consumer goods</td>
<td style="text-align: left;">Implemented starting 2018, with increases in 2025</td>
</tr>
<tr class="even">
<td style="text-align: left;">IEEPA Tariffs (fentanyl-related)</td>
<td style="text-align: left;">20% (on top of other tariffs)</td>
<td style="text-align: left;">All goods from China</td>
<td style="text-align: left;">March 4, 2025</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Reciprocal Tariff</td>
<td style="text-align: left;">125% (on top of other tariffs)</td>
<td style="text-align: left;">Most goods from China</td>
<td style="text-align: left;">April 9, 2025</td>
</tr>
<tr class="even">
<td style="text-align: left;">De Minimis Duty</td>
<td style="text-align: left;">Up to 120% or specific duties ($100-$200 per item)</td>
<td style="text-align: left;">Low-value postal shipments from China and Hong Kong</td>
<td style="text-align: left;">Effective May 2, 2025</td>
</tr>
</tbody>
</table>
<p><strong>Table 3: Summary of Current China Tariffs on Goods from the US (As of April 27th, 2025)</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Tariff Rate</th>
<th style="text-align: left;">Examples of Goods Affected</th>
<th style="text-align: left;">Effective Date</th>
<th style="text-align: left;">Type of Response</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">84%</td>
<td style="text-align: left;">Agricultural products (e.g., soybeans, pork), automobiles, etc.</td>
<td style="text-align: left;">April 10, 2025</td>
<td style="text-align: left;">Retaliatory to US Reciprocal Tariffs</td>
</tr>
<tr class="even">
<td style="text-align: left;">Various (up to 15%)</td>
<td style="text-align: left;">Coal, liquefied natural gas, crude oil, agricultural machinery</td>
<td style="text-align: left;">February 10, 2025, March 10, 2025</td>
<td style="text-align: left;">Retaliatory to earlier US tariff increases</td>
</tr>
</tbody>
</table>
<section id="works-cited" class="level4">
<h4 class="anchored" data-anchor-id="works-cited"><strong>Works cited</strong></h4>
<ol type="1">
<li>Fact Sheet: President Donald J. Trump Declares National Emergency to Increase our Competitive Edge, Protect our Sovereignty, and Strengthen our National and Economic Security - The White House, accessed April 28, 2025, <a href="https://www.whitehouse.gov/fact-sheets/2025/04/fact-sheet-president-donald-j-trump-declares-national-emergency-to-increase-our-competitive-edge-protect-our-sovereignty-and-strengthen-our-national-and-economic-security/">https://www.whitehouse.gov/fact-sheets/2025/04/fact-sheet-president-donald-j-trump-declares-national-emergency-to-increase-our-competitive-edge-protect-our-sovereignty-and-strengthen-our-national-and-economic-security/</a><br>
</li>
<li>China–United States trade war - Wikipedia, accessed April 28, 2025, <a href="https://en.wikipedia.org/wiki/China%E2%80%93United_States_trade_war">https://en.wikipedia.org/wiki/China%E2%80%93United_States_trade_war</a><br>
</li>
<li>Tariffs in the second Trump administration - Wikipedia, accessed April 28, 2025, <a href="https://en.wikipedia.org/wiki/Tariffs_in_the_second_Trump_administration">https://en.wikipedia.org/wiki/Tariffs_in_the_second_Trump_administration</a><br>
</li>
<li>What Trump’s global tariff announcement means for trade professionals, accessed April 28, 2025, <a href="https://tax.thomsonreuters.com/blog/what-trumps-global-tariff-announcement-means-for-trade-professionals/">https://tax.thomsonreuters.com/blog/what-trumps-global-tariff-announcement-means-for-trade-professionals/</a><br>
</li>
<li>See the full list of reciprocal tariffs by country from Trump’s “Liberation Day” chart, accessed April 28, 2025, <a href="https://www.cbsnews.com/news/trump-reciprocal-tariffs-liberation-day-list/">https://www.cbsnews.com/news/trump-reciprocal-tariffs-liberation-day-list/</a><br>
</li>
<li>A timeline of Trump’s tariff actions so far | PBS News, accessed April 28, 2025, <a href="https://www.pbs.org/newshour/economy/a-timeline-of-trumps-tariff-actions-so-far">https://www.pbs.org/newshour/economy/a-timeline-of-trumps-tariff-actions-so-far</a><br>
</li>
<li>Trump Tariffs: The Economic Impact of the Trump Trade War - Tax Foundation, accessed April 28, 2025, <a href="https://taxfoundation.org/research/all/federal/trump-tariffs-trade-war/">https://taxfoundation.org/research/all/federal/trump-tariffs-trade-war/</a><br>
</li>
<li>Donald Trump announces 90-day tariff pause - The Financial Express, accessed April 28, 2025, <a href="https://www.financialexpress.com/world-news/donald-trump-tariff-live-updates-china-india-us-asian-market-global-markets/3802671/">https://www.financialexpress.com/world-news/donald-trump-tariff-live-updates-china-india-us-asian-market-global-markets/3802671/</a><br>
</li>
<li>Trump announces 90-day pause on tariffs except on China - Chinadaily.com.cn, accessed April 28, 2025, <a href="https://www.chinadaily.com.cn/a/202504/10/WS67f6b59ca3104d9fd381e6f6.html">https://www.chinadaily.com.cn/a/202504/10/WS67f6b59ca3104d9fd381e6f6.html</a><br>
</li>
<li>Trump hits back with a 125% tariff in escalating trade war with China - AP News, accessed April 28, 2025, <a href="https://apnews.com/article/china-response-us-tariffs-104-d40d497f6e07ee4163d88443cb75ab3f">https://apnews.com/article/china-response-us-tariffs-104-d40d497f6e07ee4163d88443cb75ab3f</a><br>
</li>
<li>How to handle US-China tariffs and the end of de minimis - Avalara, accessed April 28, 2025, <a href="https://www.avalara.com/blog/en/north-america/2025/02/how-to-handle-us-china-tariffs-de-minimis.html">https://www.avalara.com/blog/en/north-america/2025/02/how-to-handle-us-china-tariffs-de-minimis.html</a><br>
</li>
<li>US suspends President Trump’s Reciprocal Tariff Policy for 90 days, except for China, accessed April 28, 2025, <a href="https://globaltaxnews.ey.com/news/2025-0868-us-suspends-president-trumps-reciprocal-tariff-policy-for-90-days-except-for-china">https://globaltaxnews.ey.com/news/2025-0868-us-suspends-president-trumps-reciprocal-tariff-policy-for-90-days-except-for-china</a><br>
</li>
<li>What’s Happening With Trump Tariffs? New Rates and Trade Talks - Kiplinger, accessed April 28, 2025, <a href="https://www.kiplinger.com/taxes/whats-happening-with-trump-tariffs">https://www.kiplinger.com/taxes/whats-happening-with-trump-tariffs</a><br>
</li>
<li>Trump tariff updates: US president unveils 90-day pause for most countries - Al Jazeera, accessed April 28, 2025, <a href="https://www.aljazeera.com/news/liveblog/2025/4/9/trump-tariffs-stocks-dive-as-world-braces-for-duties-to-begin-at-midnight">https://www.aljazeera.com/news/liveblog/2025/4/9/trump-tariffs-stocks-dive-as-world-braces-for-duties-to-begin-at-midnight</a><br>
</li>
<li>Trump’s Tariff-Related Trade Policy: Big Economic, Political Risks | China Digs In, accessed April 28, 2025, <a href="https://www.profarmer.com/news/policy-update/trumps-tariff-related-trade-policy-big-economic-political-risks-china-digs">https://www.profarmer.com/news/policy-update/trumps-tariff-related-trade-policy-big-economic-political-risks-china-digs</a><br>
</li>
<li>Trump limits tariffs on most nations for 90 days, raises taxes on Chinese imports - AP News, accessed April 28, 2025, <a href="https://apnews.com/article/trump-tariffs-stock-market-china-recession-deals-e8e54a68397e6829e1d27552a1d7bfb9">https://apnews.com/article/trump-tariffs-stock-market-china-recession-deals-e8e54a68397e6829e1d27552a1d7bfb9</a><br>
</li>
<li>Trump tariffs updates: China hit with 145% duties as Wall Street slides - Al Jazeera, accessed April 28, 2025, <a href="https://www.aljazeera.com/economy/liveblog/2025/4/10/trump-tariffs-live-stocks-skyrocket-as-many-duties-paused">https://www.aljazeera.com/economy/liveblog/2025/4/10/trump-tariffs-live-stocks-skyrocket-as-many-duties-paused</a><br>
</li>
<li>Amid Trump tariffs, China’s trade and economy tsar steps into spotlight, accessed April 28, 2025, <a href="https://m.economictimes.com/news/international/business/amid-trump-tariffs-chinas-trade-and-economy-tsar-steps-into-spotlight/articleshow/120681528.cms?UTM_Source=Google_Newsstand&amp;UTM_Campaign=RSS_Feed&amp;UTM_Medium=Referral">https://m.economictimes.com/news/international/business/amid-trump-tariffs-chinas-trade-and-economy-tsar-steps-into-spotlight/articleshow/120681528.cms?UTM_Source=Google_Newsstand&amp;UTM_Campaign=RSS_Feed&amp;UTM_Medium=Referral</a><br>
</li>
<li>Chinese firms race to open US factories as Trump’s tariff war hits home - Business Standard, accessed April 28, 2025, <a href="https://www.business-standard.com/world-news/china-manufacturers-move-us-factories-production-tariff-war-donald-trump-125042700109_1.html">https://www.business-standard.com/world-news/china-manufacturers-move-us-factories-production-tariff-war-donald-trump-125042700109_1.html</a><br>
</li>
<li>US Treasury secretary says trade war with China is not ‘sustainable’ - AP News, accessed April 28, 2025, <a href="https://apnews.com/article/tariffs-trade-taxes-trump-china-bessent-treasury-66668fa26957ece530a250fa8ea19faa">https://apnews.com/article/tariffs-trade-taxes-trump-china-bessent-treasury-66668fa26957ece530a250fa8ea19faa</a><br>
</li>
<li>China warns countries against making trade deals with the US unfavorable to Beijing - AP News, accessed April 28, 2025, <a href="https://apnews.com/article/chian-us-tariffs-retaliation-18b3da9bed1aa1b3ee3a79e91c197730">https://apnews.com/article/chian-us-tariffs-retaliation-18b3da9bed1aa1b3ee3a79e91c197730</a><br>
</li>
<li>Fact Sheet: President Donald J. Trump Closes De Minimis Exemptions to Combat China’s Role in America’s Synthetic Opioid Crisis - The White House, accessed April 28, 2025, <a href="https://www.whitehouse.gov/fact-sheets/2025/04/fact-sheet-president-donald-j-trump-closes-de-minimis-exemptions-to-combat-chinas-role-in-americas-synthetic-opioid-crisis/">https://www.whitehouse.gov/fact-sheets/2025/04/fact-sheet-president-donald-j-trump-closes-de-minimis-exemptions-to-combat-chinas-role-in-americas-synthetic-opioid-crisis/</a><br>
</li>
<li>Most Americans expect higher prices as a result of Trump’s tariffs, a new AP-NORC poll finds - AP News, accessed April 28, 2025, <a href="https://apnews.com/article/trump-economy-poll-tariffs-inflation-prices-recession-1d320115e8801e4970bd5cccf2742fc4">https://apnews.com/article/trump-economy-poll-tariffs-inflation-prices-recession-1d320115e8801e4970bd5cccf2742fc4</a><br>
</li>
<li>Bloomberg: Trump floats cutting China tariffs substantially in trade deal : r/stocks - Reddit, accessed April 28, 2025, <a href="https://www.reddit.com/r/stocks/comments/1k5q7qb/bloomberg_trump_floats_cutting_china_tariffs/">https://www.reddit.com/r/stocks/comments/1k5q7qb/bloomberg_trump_floats_cutting_china_tariffs/</a><br>
</li>
<li>Trump Wants China Concessions, Shein Hikes US Prices | Bloomberg: The Asia Trade 4/28/25 - YouTube, accessed April 28, 2025, <a href="https://www.youtube.com/watch?v=xjOHWzDNkxs">https://www.youtube.com/watch?v=xjOHWzDNkxs</a><br>
</li>
<li>U.S. Tariffs Update – April 14, 2025 - Fredrikson &amp; Byron P.A., accessed April 28, 2025, <a href="https://www.fredlaw.com/alert-u-s-tariffs-update-april-14-2025">https://www.fredlaw.com/alert-u-s-tariffs-update-april-14-2025</a><br>
</li>
<li>Trump threatens more tariffs on China as global markets shudder - AP News, accessed April 28, 2025, <a href="https://apnews.com/article/trump-tariffs-stock-market-52a00ea2bb92a067ee72343941b02cd4">https://apnews.com/article/trump-tariffs-stock-market-52a00ea2bb92a067ee72343941b02cd4</a><br>
</li>
<li>Experts warn Trump’s trade war with China could erupt into a cold …, accessed April 28, 2025, <a href="https://www.independent.co.uk/news/world/americas/us-politics/trump-china-tariffs-cold-war-b2736957.html">https://www.independent.co.uk/news/world/americas/us-politics/trump-china-tariffs-cold-war-b2736957.html</a><br>
</li>
<li>‘Not seeking trade imbalance’: China releases white paper on trade …, accessed April 28, 2025, <a href="https://www.business-standard.com/world-news/china-us-trade-white-paper-2025-tariffs-dispute-phase-one-125040900941_1.html">https://www.business-standard.com/world-news/china-us-trade-white-paper-2025-tariffs-dispute-phase-one-125040900941_1.html</a><br>
</li>
<li>‘Unilateralist and protectionist acts’: 10 key points from China’s White …, accessed April 28, 2025, <a href="https://timesofindia.indiatimes.com/world/china/unilateralist-and-protectionist-acts-10-key-points-from-chinas-white-paper-on-trumps-tariff/articleshow/120123443.cms">https://timesofindia.indiatimes.com/world/china/unilateralist-and-protectionist-acts-10-key-points-from-chinas-white-paper-on-trumps-tariff/articleshow/120123443.cms</a><br>
</li>
<li>China issues white paper outlining stance on economic ties with …, accessed April 28, 2025, <a href="https://news.cgtn.com/news/2025-04-09/China-issues-white-paper-outlining-stance-on-economic-ties-with-U-S--1CqH8oO3BSg/p.html">https://news.cgtn.com/news/2025-04-09/China-issues-white-paper-outlining-stance-on-economic-ties-with-U-S–1CqH8oO3BSg/p.html</a><br>
</li>
<li>China’s State Council Releases White Paper “China’s Position on Certain Issues in China-US Economic and Trade Relations” - China Continuously Improves IP Protection and Prohibits Forced Technology Transfer - China IP Law Update, accessed April 28, 2025, <a href="https://www.chinaiplawupdate.com/2025/04/chinas-state-council-releases-white-paper-chinas-position-on-certain-issues-in-china-us-economic-and-trade-relations-china-continuously-improves-ip-protection-and-prohibits-forced-technology/">https://www.chinaiplawupdate.com/2025/04/chinas-state-council-releases-white-paper-chinas-position-on-certain-issues-in-china-us-economic-and-trade-relations-china-continuously-improves-ip-protection-and-prohibits-forced-technology/</a><br>
</li>
<li>China releases white paper on China-US economic, trade relations …, accessed April 28, 2025, <a href="http://english.scio.gov.cn/m/whitepapers/2025-04/09/content_117814327.html">http://english.scio.gov.cn/m/whitepapers/2025-04/09/content_117814327.html</a><br>
</li>
<li>Full text: China’s Position on Some Issues Concerning China-US Economic and Trade Relations | english.scio.gov.cn, accessed April 28, 2025, <a href="http://english.scio.gov.cn/whitepapers/2025-04/09/content_117814362.html">http://english.scio.gov.cn/whitepapers/2025-04/09/content_117814362.html</a><br>
</li>
<li>China releases white paper on China-U.S. economic, trade relations - Xinhua, accessed April 28, 2025, <a href="https://english.news.cn/20250409/7458b316f22944fe9059d229d4d22ed3/c.html">https://english.news.cn/20250409/7458b316f22944fe9059d229d4d22ed3/c.html</a><br>
</li>
<li>China releases white paper on China-US economic, trade relations - Chinadaily.com.cn, accessed April 28, 2025, <a href="https://www.chinadaily.com.cn/a/202504/09/WS67f61b3fa3104d9fd381e5cf.html">https://www.chinadaily.com.cn/a/202504/09/WS67f61b3fa3104d9fd381e5cf.html</a><br>
</li>
<li>Full text: China’s Position on Some Issues Concerning China-US Economic, Trade Relations, accessed April 28, 2025, <a href="https://www.globaltimes.cn/page/202504/1331740.shtml">https://www.globaltimes.cn/page/202504/1331740.shtml</a><br>
</li>
<li>China waives tariffs on some US goods, but denies Trump’s claim that talks are under way, accessed April 28, 2025, <a href="https://www.straitstimes.com/asia/east-asia/china-waives-tariffs-on-some-us-goods-but-denies-trumps-claim-that-talks-are-underway">https://www.straitstimes.com/asia/east-asia/china-waives-tariffs-on-some-us-goods-but-denies-trumps-claim-that-talks-are-underway</a><br>
</li>
<li>China’s latest response on tariffs sends the market reeling - TheStreet, accessed April 28, 2025, <a href="https://www.thestreet.com/crypto/policy/chinas-latest-response-on-tariffs-sends-shock-into-the-market">https://www.thestreet.com/crypto/policy/chinas-latest-response-on-tariffs-sends-shock-into-the-market</a><br>
</li>
<li>US-China Tariff War Escalates | Global Trade War | Xi Jinping | N18G - YouTube, accessed April 28, 2025, <a href="https://www.youtube.com/watch?v=PH0TtM7405o">https://www.youtube.com/watch?v=PH0TtM7405o</a><br>
</li>
<li>Wall Street Journal says China called Trump’s bluff, wins this round of tariff war but the good news is… - The Times of India, accessed April 28, 2025, <a href="https://timesofindia.indiatimes.com/world/us/wall-street-journal-says-china-called-trumps-bluff-wins-this-round-but-the-good-news-is-/articleshow/120591261.cms">https://timesofindia.indiatimes.com/world/us/wall-street-journal-says-china-called-trumps-bluff-wins-this-round-but-the-good-news-is-/articleshow/120591261.cms</a><br>
</li>
<li>Trump tariffs: President vents at China over Boeing as Beijing denies claims of trade deal talks | The Independent, accessed April 28, 2025, <a href="https://www.independent.co.uk/news/world/americas/us-politics/trump-tariffs-china-live-updates-auto-recession-b2738585.html">https://www.independent.co.uk/news/world/americas/us-politics/trump-tariffs-china-live-updates-auto-recession-b2738585.html</a><br>
</li>
<li>President Trump says U.S. met this morning with China, declines to identify individuals involved - YouTube, accessed April 28, 2025, <a href="https://www.youtube.com/watch?v=o_wHHVnBhgE">https://www.youtube.com/watch?v=o_wHHVnBhgE</a><br>
</li>
<li>China considers exempting some goods from US tariffs - Eric Cotter …, accessed April 28, 2025, <a href="https://cotteraccounting.com/2025/04/25/china-considers-exempting-some-goods-from-us-tariffs/">https://cotteraccounting.com/2025/04/25/china-considers-exempting-some-goods-from-us-tariffs/</a><br>
</li>
<li>China mulling US tariff exemptions - Taipei Times, accessed April 28, 2025, <a href="https://www.taipeitimes.com/News/biz/archives/2025/04/26/2003835824">https://www.taipeitimes.com/News/biz/archives/2025/04/26/2003835824</a><br>
</li>
<li>China considers exempting some goods from US tariffs - The Standard, accessed April 28, 2025, <a href="https://www.thestandard.com.hk/china-news/article/301176/China-considers-exempting-some-goods-from-US-tariffs">https://www.thestandard.com.hk/china-news/article/301176/China-considers-exempting-some-goods-from-US-tariffs</a><br>
</li>
<li>China May Exempt Some US Goods From Tariffs as Costs Rise : r/StockMarket - Reddit, accessed April 28, 2025, <a href="https://www.reddit.com/r/StockMarket/comments/1k7jjwz/china_may_exempt_some_us_goods_from_tariffs_as/">https://www.reddit.com/r/StockMarket/comments/1k7jjwz/china_may_exempt_some_us_goods_from_tariffs_as/</a><br>
</li>
<li>Tariff uncertainty: Impacts on markets and portfolios - BlackRock, accessed April 28, 2025, <a href="https://www.blackrock.com/us/financial-professionals/insights/tariffs-and-investment-portfolios">https://www.blackrock.com/us/financial-professionals/insights/tariffs-and-investment-portfolios</a><br>
</li>
<li>Wall Street falls again as losses wipe out all post-election gains for the S&amp;P 500 | AP News, accessed April 28, 2025, <a href="https://apnews.com/article/stocks-markets-rates-tariffs-trump-1ca865fa6abcca716b5e7c9281ea6e07">https://apnews.com/article/stocks-markets-rates-tariffs-trump-1ca865fa6abcca716b5e7c9281ea6e07</a><br>
</li>
<li>Taking Trump’s Tariffs Seriously: The Fiscal and Economic Impact for NYC, accessed April 28, 2025, <a href="https://comptroller.nyc.gov/reports/taking-trumps-tariffs-seriously-the-fiscal-and-economic-impact-for-nyc/">https://comptroller.nyc.gov/reports/taking-trumps-tariffs-seriously-the-fiscal-and-economic-impact-for-nyc/</a><br>
</li>
<li>Trump threatens to impose an additional 50% tariff on China - CBS News, accessed April 28, 2025, <a href="https://www.cbsnews.com/news/trump-tariffs-china-50-percent-tariff-retaliatory/">https://www.cbsnews.com/news/trump-tariffs-china-50-percent-tariff-retaliatory/</a><br>
</li>
<li>China learned from Trump’s first trade war and changed its tactics when tariffs came again, accessed April 28, 2025, <a href="https://www.bnnbloomberg.ca/business/international/2025/03/09/china-learned-from-trumps-first-trade-war-and-changed-its-tactics-when-tariffs-came-again/">https://www.bnnbloomberg.ca/business/international/2025/03/09/china-learned-from-trumps-first-trade-war-and-changed-its-tactics-when-tariffs-came-again/</a><br>
</li>
<li>China Responds To Donald Trump’s Tariff Backflip | 10 News First - YouTube, accessed April 28, 2025, <a href="https://www.youtube.com/watch?v=AcwdqisUODw">https://www.youtube.com/watch?v=AcwdqisUODw</a><br>
</li>
<li>US-China tariff tensions are not just a trade spat, expert says - YouTube, accessed April 28, 2025, <a href="https://www.youtube.com/watch?v=ZLlV26EldEE">https://www.youtube.com/watch?v=ZLlV26EldEE</a><br>
</li>
<li>US and global economic outlook deteriorates in Trump trade war …, accessed April 28, 2025, <a href="https://apnews.com/article/recession-imf-economy-tariffs-5ec37492c9fac499923c094776b87552">https://apnews.com/article/recession-imf-economy-tariffs-5ec37492c9fac499923c094776b87552</a><br>
</li>
<li>Tariffs &amp; trade war: Market commentary | Robeco Global, accessed April 28, 2025, <a href="https://www.robeco.com/en-int/insights/2025/04/tariffs-trade-war-market-commentary">https://www.robeco.com/en-int/insights/2025/04/tariffs-trade-war-market-commentary</a><br>
</li>
<li>China and the Impact of “Liberation Day” Tariffs - CSIS, accessed April 28, 2025, <a href="https://www.csis.org/analysis/china-and-impact-liberation-day-tariffs">https://www.csis.org/analysis/china-and-impact-liberation-day-tariffs</a><br>
</li>
<li>Trump’s Trade War is a Major Economic and Strategic Blunder, accessed April 28, 2025, <a href="https://www.americanprogress.org/article/trumps-trade-war-is-a-major-economic-and-strategic-blunder/">https://www.americanprogress.org/article/trumps-trade-war-is-a-major-economic-and-strategic-blunder/</a><br>
</li>
<li>Trump-China trade war: Which US companies could be worst hit …, accessed April 28, 2025, <a href="https://www.aljazeera.com/news/2025/4/15/trump-china-trade-war-which-us-companies-could-be-worst-hit">https://www.aljazeera.com/news/2025/4/15/trump-china-trade-war-which-us-companies-could-be-worst-hit</a><br>
</li>
<li>PIIE experts react to Trump’s tariffs announced April 2, accessed April 28, 2025, <a href="https://www.piie.com/blogs/realtime-economics/2025/piie-experts-react-trumps-tariffs-announced-april-2">https://www.piie.com/blogs/realtime-economics/2025/piie-experts-react-trumps-tariffs-announced-april-2</a><br>
</li>
<li>What Trump’s Trade War Would Mean, in Nine Charts - Council on Foreign Relations, accessed April 28, 2025, <a href="https://www.cfr.org/article/what-trumps-trade-war-would-mean-nine-charts">https://www.cfr.org/article/what-trumps-trade-war-would-mean-nine-charts</a><br>
</li>
<li>Xi Aims to Mend Ties With Europe as Trump Alienates Trading Partners - YouTube, accessed April 28, 2025, <a href="https://www.youtube.com/watch?v=4i5jL5xK9Cg">https://www.youtube.com/watch?v=4i5jL5xK9Cg</a></li>
</ol>


<!-- -->

</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const cellDetails = window.document.querySelectorAll(".cell details.code-fold");
        for (let i=0; i<cellDetails.length; i++) {
          const details = cellDetails[i];
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell div.sourceCode.cell-code");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/shepotylo\.com");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Trump Trade War Diary — Days 81–100"</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="an">description:</span><span class="co"> "Recent developments in the trade relationship between the United States and China concerning tariffs within the last 10 days have been marked by continued tension, particularly with the US maintaining and escalating tariff pressure on China while adopting a…"</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> "2025-04-11"</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="an">categories:</span><span class="co"> [trade-wars, trump-trade-war-diary]</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">## US-China Trade War Escalation</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu"># **Recent Developments in US Tariffs Against China and China's Responses (April 17th to April 27th, 2025\)**</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>**1\. Executive Summary**</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>Recent developments in the trade relationship between the United States and China concerning tariffs within the last 10 days have been marked by continued tension, particularly with the US maintaining and escalating tariff pressure on China while adopting a temporary pause with most other trading partners. Key US policy changes during this period, building on earlier actions, include the maintenance of significantly elevated tariff rates on Chinese imports and the formal announcement of the elimination of the "de minimis" exemption for low-value goods from China and Hong Kong. In response, China has reiterated its strong opposition through the release of a comprehensive White Paper on US trade, continued to deny US claims of ongoing tariff negotiations, and indicated a potential consideration of targeted tariff exemptions on certain essential US goods. The overarching trend suggests a persistent and deepening trade conflict between the two economic giants, carrying significant implications for global trade, economic stability, and geopolitical relations.</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>**2\. Background: Trump's Tariff Policy Against China (Pre-Last 10 Days)**</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>The imposition of tariffs by the United States on goods imported from China has been a defining feature of trade policy under President Trump, originating from stated objectives such as addressing substantial trade deficits and combating the alleged theft of US intellectual property.1 The initial major step in this direction occurred in 2018 with the implementation of tariffs under Section 301 of the Trade Act of 1974, targeting a wide array of Chinese products, including electronics, machinery, and consumer goods.2 Over time, the scope and rates of these tariffs expanded, affecting sectors like steel, aluminum, and, more recently, automobiles.3 Prior to the 10-day period under review, the year 2025 had already witnessed significant increases in tariffs on Chinese imports. Notably, on April 2, 2025, President Trump announced what was termed "Liberation Day," a significant escalation involving a baseline tariff of 10% on almost all imports and higher "reciprocal tariffs" levied on specific countries based on their trade balances with the US.3 This announcement included a substantial initial increase in tariffs on goods originating from China, setting the stage for the developments observed within the subsequent 10 days.</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>**3\. US Policy Changes on China Tariffs in the Last 10 Days (From approximately April 17th to April 27th, 2025\)**</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>**3.1. Initial High Tariffs and Subsequent Pause**</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>The implementation of the "reciprocal tariffs" on April 9th marked a significant point in the ongoing trade dispute. This included an initial tariff of 34% on Chinese imports, which, when added to existing levies such as the 20% tariff related to fentanyl trafficking and earlier increases, brought the total tariff rate on many Chinese goods to 104%.4 However, on the very same day, the Trump administration announced a 90-day pause on these newly implemented reciprocal tariffs for the majority of countries.3 Critically, China was explicitly excluded from this temporary reprieve, signaling a clear and targeted intensification of the trade confrontation with Beijing.3 Coinciding with the announcement of the pause for other nations, the US administration further escalated the trade war with China by increasing the tariff rate on Chinese imports to 125%.5 This rapid sequence of policy changes underscored a strategic decision to single out China for heightened tariff pressure. Subsequently, on April 10th, the White House clarified that the cumulative tariff burden on goods imported from China had reached an unprecedented 145%, highlighting the severity of the trade measures specifically targeting Beijing.5</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>**3.2. De Minimis Exemption Closure**</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>Within the 10-day period, the US administration formally announced the decision to eliminate the "de minimis" exemption for low-value imports originating from China and Hong Kong, with the policy set to take effect on May 2, 2025<span class="sc">\.</span>4 This policy change entails a significant increase in duties applied to postal items valued at or under $800 arriving from mainland China and Hong Kong. These duties were set to reach as high as 120% of the item's value or a specific duty of $100 per item initially, with further increases to $200 per item planned for June 1, 2025<span class="sc">\.</span>11 The Trump administration explicitly linked this policy decision to its stated objective of combating China's perceived role in the ongoing synthetic opioid crisis in the United States, asserting that deceptive shipping practices were being exploited through the de minimis exemption.22 This action demonstrates a more targeted approach in the US trade strategy towards China, extending beyond broad tariff increases to address specific concerns related to illicit goods flows.</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>**3.3. Rhetoric and Signals Regarding Future Actions**</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>Throughout the last 10 days, statements from US officials provided insights into the administration's thinking regarding the trade war with China. Treasury Secretary Scott Bessent, in remarks likely made just before or at the beginning of this period, described the ongoing tariff showdown against China as "unsustainable," suggesting a potential for de-escalation in the future.20 Similarly, President Trump indicated that the final tariff rate applied to China would eventually be reduced "substantially" from the current peak of 145%, offering a glimpse of a possible long-term scenario, although no immediate policy changes reflecting this sentiment were implemented within the timeframe.20 However, towards the end of the 10-day window (as indicated by reports from April 28th, slightly outside the strict timeframe but indicative of ongoing sentiment), President Trump expressed skepticism about implementing another pause on tariffs and reiterated his demand for concessions from China, suggesting a continued stance of pressure.25 Furthermore, the possibility of imposing additional tariffs targeting specific strategic sectors, such as semiconductors and pharmaceuticals, remained under consideration, as reported earlier in April.4 These various signals suggest a complex and potentially evolving US strategy, balancing an acknowledgment of the long-term unsustainability of the current high tariffs with a continued commitment to using them as leverage to achieve trade concessions from China.</span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>**4\. China's Response to US Tariff Actions in the Last 10 Days**</span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a>**4.1. Immediate Retaliation and Strong Rhetoric**</span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a>In direct response to the US implementation of "reciprocal tariffs," China announced on April 9th that it would raise its tariffs on US goods to 84%, effective from April 10th.5 This move to match the initial US reciprocal tariff rate demonstrated China's unwavering policy of retaliating in kind to US tariff actions. China's Ministry of Finance issued a strong condemnation of the US escalation, characterizing it as a "mistake on top of a mistake," clearly signaling Beijing's firm opposition to the US tariff policy.14 Furthermore, Chinese authorities reiterated their resolute stance against the US tariffs, vowing to "fight to the end" and underscoring their determination to withstand the pressure and their readiness to implement further countermeasures if necessary.6</span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a>**4.2. China's White Paper on US Trade**</span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a>A significant aspect of China's response at the beginning of the 10-day period was the release of a comprehensive White Paper on April 9th, formally titled "China's Position on Some Issues Concerning China-US Economic and Trade Relations".8 This document provided a detailed articulation of China's official perspective on its economic and trade relationship with the United States. Key arguments presented in the White Paper included an emphasis on the mutually beneficial nature of bilateral trade, assertions of China's adherence to the 2020 trade agreement, and strong criticisms of what China views as US unilateralism and protectionist trade practices.29 The White Paper also explicitly called for the resolution of trade disputes through dialogue and cooperation based on principles of equality and mutual benefit, outlining China's preferred approach to de-escalating the ongoing conflict.29 The release of this document served as a formal and comprehensive diplomatic response to the escalating trade tensions.</span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a>**4.3. Repeated Denial of Ongoing Tariff Negotiations**</span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a>Throughout the last 10 days, China consistently and firmly denied claims made by the US administration suggesting that active tariff negotiations were taking place between the two nations.18 The Chinese Embassy in Washington issued a direct and unambiguous statement via social media, explicitly asserting that "China and the US are NOT having any consultation or negotiation on <span class="sc">\#</span>tariffs" and urging the US to refrain from creating confusion on this matter.38 Further reinforcing this stance, a spokesperson for China's Ministry of Commerce dismissed US claims of progress in negotiations as "groundless" and lacking any "factual basis".42 This consistent denial highlights a significant divergence in the narratives presented by the two countries regarding the status of their trade relationship.</span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a>**4.4. Consideration of Tariff Exemptions on Some US Goods**</span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a>Towards the end of the 10-day period, reports emerged indicating that China was actively considering exempting certain US imports from its retaliatory tariffs.18 These potential exemptions reportedly included essential items such as medical equipment, specific industrial chemicals like ethane, aircraft leasing payments, and a selection of semiconductor products, although not memory chips.18 This consideration is likely driven by growing concerns within China about the adverse impact of the ongoing trade war on its own critical industries and the potential for disruptions to vital supply chains that rely on specific US-made components or materials.39 The Chinese government has reportedly been soliciting input from local companies to identify specific US imports for which tariff relief would be most beneficial, suggesting a targeted and pragmatic approach to mitigating the domestic economic fallout.39 This potential move indicates a nuanced approach by China, balancing its firm stance against US tariffs with a recognition of the need to protect its own economic interests.</span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a>**4.5. Strong Warning Against Trade Deals at China's Expense**</span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a>China reiterated its strong warning to other countries against entering into trade agreements with the United States that could potentially undermine or negatively impact China's economic interests.20 The Commerce Ministry explicitly stated, "China firmly opposes any party reaching a deal at the expense of China's interests," underscoring Beijing's determination to protect its position in the global trade landscape.20 This stance reflects China's broader strategic concerns extending beyond its direct trade relationship with the US, indicating its efforts to prevent the US from forming alliances or striking deals that could isolate or disadvantage China in the international trade arena.</span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a>**4.6. Continued Potential for Further Retaliation and Use of Export Controls**</span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a>The potential for China to implement further retaliatory measures, including the use of export controls, remains a significant factor in the ongoing trade dispute.3 Specifically, China possesses leverage through its dominance in the production of rare earth minerals, which are critical for various high-tech industries globally. The existing practice of China adding US firms to lists subject to export controls and trade sanctions demonstrates its willingness to employ non-tariff measures in response to US actions.5 These potential actions highlight the multifaceted nature of China's response capabilities beyond just the imposition of tariffs.</span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a>**5\. Analysis and Implications**</span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a>**5.1. Intensifying Economic Impact on Both Countries**</span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-64"><a href="#cb1-64" aria-hidden="true" tabindex="-1"></a>The sustained high levels of tariffs imposed by both the United States and China are likely to have an increasingly negative impact on their respective economies. For US businesses and consumers, the escalating tariffs translate to higher import costs and, consequently, increased prices for a wide range of goods, potentially leading to inflationary pressures.1 Supply chains, particularly those heavily reliant on Chinese imports, face disruptions, potentially affecting production and availability of goods.1 On the other side, Chinese manufacturers and exporters are facing significant challenges due to the drastically reduced access to the crucial US market, a direct consequence of the 145% tariff rate on many of their goods.2 This is further compounded by the impact of China's own retaliatory tariffs on US goods, affecting US exporters as well.2 International organizations, such as the International Monetary Fund, and numerous economic analysts have expressed growing concerns that these escalating tariffs could fuel inflation in both the US and China, and contribute to a broader slowdown in the global economy, underscoring the interconnected nature of international trade.4</span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-66"><a href="#cb1-66" aria-hidden="true" tabindex="-1"></a>**5.2. Accelerating Reshaping of Global Supply Chains**</span>
<span id="cb1-67"><a href="#cb1-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-68"><a href="#cb1-68" aria-hidden="true" tabindex="-1"></a>The sustained high levels of tariffs and the uncertainty surrounding the future of US-China trade policy are likely to further accelerate the ongoing trend of businesses re-evaluating and restructuring their global supply chains. Faced with tariffs as high as 145%, some Chinese firms are exploring the possibility of establishing manufacturing facilities within the United States or in other countries that are not subject to these tariffs, aiming to circumvent the punitive duties.1 Simultaneously, US companies that have historically relied on China for sourcing goods are increasingly seeking to diversify their supply chains, looking for alternative suppliers in other nations to mitigate the impact of the tariffs.1 These shifts in sourcing and production are likely to have significant long-term consequences, potentially leading to increased costs for consumers as supply chains are reconfigured, the emergence of new regional trade hubs, and a fundamental reshaping of the global trade patterns that have been established over several decades.1</span>
<span id="cb1-69"><a href="#cb1-69" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-70"><a href="#cb1-70" aria-hidden="true" tabindex="-1"></a>**5.3. Deepening Geopolitical Tensions and Strategic Competition**</span>
<span id="cb1-71"><a href="#cb1-71" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-72"><a href="#cb1-72" aria-hidden="true" tabindex="-1"></a>The ongoing trade war is not occurring in isolation; it is a significant factor contributing to the further deterioration of the broader relationship between the United States and China. The escalating tariffs and the accompanying rhetoric are exacerbating existing geopolitical tensions and potentially pushing the two nations towards a more confrontational stance, reminiscent of a "cold war" dynamic.2 This competition extends beyond trade into critical areas such as technology, security, and international diplomacy.2 In response, China is strategically seeking to strengthen its trade and diplomatic ties with other regions around the world, positioning itself as a proponent of multilateralism and increasingly criticizing the US approach to international trade and global governance as unilateral and protectionist.2 The trade war, therefore, is not just an economic dispute but an integral part of a larger strategic competition with far-reaching geopolitical implications.</span>
<span id="cb1-73"><a href="#cb1-73" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-74"><a href="#cb1-74" aria-hidden="true" tabindex="-1"></a>**6\. Conclusion**</span>
<span id="cb1-75"><a href="#cb1-75" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-76"><a href="#cb1-76" aria-hidden="true" tabindex="-1"></a>In the last 10 days, US policy on tariffs against China has remained firmly in an escalatory mode, characterized by the maintenance of a 145% tariff rate on many Chinese goods and the notable exclusion of China from the 90-day pause on reciprocal tariffs granted to most other trading partners. Additionally, the US announced the impending closure of the de minimis exemption for low-value imports from China and Hong Kong, signaling a further tightening of trade restrictions. China's response during this period has been multifaceted, including an immediate retaliatory tariff increase to 84% on US goods, a comprehensive diplomatic offensive through the release of a White Paper outlining its position on the trade dispute, and consistent denials of US claims regarding ongoing tariff negotiations. Notably, there were also reports suggesting that China is considering targeted tariff exemptions on certain essential US goods, indicating a potential pragmatic approach to mitigating the domestic economic impact of the trade war. Despite these nuanced considerations, the overall trajectory of US-China trade relations remains fraught with tension and uncertainty. The conflicting signals emanating from both sides regarding the potential for de-escalation versus continued confrontation underscore the fluidity of the situation. The possibility of further tariff increases by the US or additional retaliatory measures from China cannot be discounted. Looking ahead, the US-China trade relationship appears poised to remain contentious, with significant potential for negative repercussions on the global economy, the stability of international supply chains, and the broader geopolitical landscape.</span>
<span id="cb1-77"><a href="#cb1-77" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-78"><a href="#cb1-78" aria-hidden="true" tabindex="-1"></a>**7\. Potential Key Tables for the Report:**</span>
<span id="cb1-79"><a href="#cb1-79" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-80"><a href="#cb1-80" aria-hidden="true" tabindex="-1"></a>**Table 1: Timeline of Key US-China Tariff Actions (April 9th \- April 27th, 2025\)**</span>
<span id="cb1-81"><a href="#cb1-81" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-82"><a href="#cb1-82" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Date <span class="pp">|</span> US Action <span class="pp">|</span> China's Response <span class="pp">|</span></span>
<span id="cb1-83"><a href="#cb1-83" aria-hidden="true" tabindex="-1"></a><span class="pp">| :----</span> <span class="pp">| :----</span> <span class="pp">| :----</span> <span class="pp">|</span></span>
<span id="cb1-84"><a href="#cb1-84" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> April 9th <span class="pp">|</span> Implementation of 34% Reciprocal Tariff on China, increasing total tariff to 104% <span class="pp">|</span> Announced retaliatory tariff increase to 84% on US goods, effective April 10th <span class="pp">|</span></span>
<span id="cb1-85"><a href="#cb1-85" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> April 9th <span class="pp">|</span> Announcement of 90-day pause on Reciprocal Tariffs for most countries, excluding China <span class="pp">|</span> Released White Paper on US Trade outlining its position and calling for dialogue <span class="pp">|</span></span>
<span id="cb1-86"><a href="#cb1-86" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> April 9th <span class="pp">|</span> Increased tariff on China to 125% <span class="pp">|</span> Continued to deny US claims of ongoing tariff negotiations <span class="pp">|</span></span>
<span id="cb1-87"><a href="#cb1-87" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> April 10th <span class="pp">|</span> White House clarified total tariff rate on Chinese imports reached 145% <span class="pp">|</span>  <span class="pp">|</span></span>
<span id="cb1-88"><a href="#cb1-88" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Approx. April 25th <span class="pp">|</span> Announcement (or increased prominence of earlier announcement) of De Minimis Exemption Closure for China and Hong Kong (effective May 2nd) <span class="pp">|</span> Reports emerged suggesting consideration of targeted tariff exemptions on some essential US goods (medical equipment, some chemicals, etc.) <span class="pp">|</span></span>
<span id="cb1-89"><a href="#cb1-89" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-90"><a href="#cb1-90" aria-hidden="true" tabindex="-1"></a>**Table 2: Summary of Current US Tariffs on Goods from China (As of April 27th, 2025\)**</span>
<span id="cb1-91"><a href="#cb1-91" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-92"><a href="#cb1-92" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Tariff Type <span class="pp">|</span> Estimated Total Rate <span class="pp">|</span> Examples of Goods Affected <span class="pp">|</span> Effective Date <span class="pp">|</span></span>
<span id="cb1-93"><a href="#cb1-93" aria-hidden="true" tabindex="-1"></a><span class="pp">| :----</span> <span class="pp">| :----</span> <span class="pp">| :----</span> <span class="pp">| :----</span> <span class="pp">|</span></span>
<span id="cb1-94"><a href="#cb1-94" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Section 301 Tariffs (various tranches) <span class="pp">|</span> 7.5% to 100% (depending on the product) <span class="pp">|</span> Electronics, machinery, consumer goods <span class="pp">|</span> Implemented starting 2018, with increases in 2025 <span class="pp">|</span></span>
<span id="cb1-95"><a href="#cb1-95" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> IEEPA Tariffs (fentanyl-related) <span class="pp">|</span> 20% (on top of other tariffs) <span class="pp">|</span> All goods from China <span class="pp">|</span> March 4, 2025 <span class="pp">|</span></span>
<span id="cb1-96"><a href="#cb1-96" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Reciprocal Tariff <span class="pp">|</span> 125% (on top of other tariffs) <span class="pp">|</span> Most goods from China <span class="pp">|</span> April 9, 2025 <span class="pp">|</span></span>
<span id="cb1-97"><a href="#cb1-97" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> De Minimis Duty <span class="pp">|</span> Up to 120% or specific duties ($100-$200 per item) <span class="pp">|</span> Low-value postal shipments from China and Hong Kong <span class="pp">|</span> Effective May 2, 2025 <span class="pp">|</span></span>
<span id="cb1-98"><a href="#cb1-98" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-99"><a href="#cb1-99" aria-hidden="true" tabindex="-1"></a>**Table 3: Summary of Current China Tariffs on Goods from the US (As of April 27th, 2025\)**</span>
<span id="cb1-100"><a href="#cb1-100" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-101"><a href="#cb1-101" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Tariff Rate <span class="pp">|</span> Examples of Goods Affected <span class="pp">|</span> Effective Date <span class="pp">|</span> Type of Response <span class="pp">|</span></span>
<span id="cb1-102"><a href="#cb1-102" aria-hidden="true" tabindex="-1"></a><span class="pp">| :----</span> <span class="pp">| :----</span> <span class="pp">| :----</span> <span class="pp">| :----</span> <span class="pp">|</span></span>
<span id="cb1-103"><a href="#cb1-103" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 84% <span class="pp">|</span> Agricultural products (e.g., soybeans, pork), automobiles, etc. <span class="pp">|</span> April 10, 2025 <span class="pp">|</span> Retaliatory to US Reciprocal Tariffs <span class="pp">|</span></span>
<span id="cb1-104"><a href="#cb1-104" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Various (up to 15%) <span class="pp">|</span> Coal, liquefied natural gas, crude oil, agricultural machinery <span class="pp">|</span> February 10, 2025, March 10, 2025 <span class="pp">|</span> Retaliatory to earlier US tariff increases <span class="pp">|</span></span>
<span id="cb1-105"><a href="#cb1-105" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-106"><a href="#cb1-106" aria-hidden="true" tabindex="-1"></a><span class="fu">#### **Works cited**</span></span>
<span id="cb1-107"><a href="#cb1-107" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-108"><a href="#cb1-108" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>Fact Sheet: President Donald J. Trump Declares National Emergency to Increase our Competitive Edge, Protect our Sovereignty, and Strengthen our National and Economic Security <span class="sc">\-</span> The White House, accessed April 28, 2025, <span class="co">[</span><span class="ot">https://www.whitehouse.gov/fact-sheets/2025/04/fact-sheet-president-donald-j-trump-declares-national-emergency-to-increase-our-competitive-edge-protect-our-sovereignty-and-strengthen-our-national-and-economic-security/</span><span class="co">](https://www.whitehouse.gov/fact-sheets/2025/04/fact-sheet-president-donald-j-trump-declares-national-emergency-to-increase-our-competitive-edge-protect-our-sovereignty-and-strengthen-our-national-and-economic-security/)</span>  </span>
<span id="cb1-109"><a href="#cb1-109" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>China–United States trade war <span class="sc">\-</span> Wikipedia, accessed April 28, 2025, <span class="co">[</span><span class="ot">https://en.wikipedia.org/wiki/China%E2%80%93United\_States\_trade\_war</span><span class="co">](https://en.wikipedia.org/wiki/China%E2%80%93United_States_trade_war)</span>  </span>
<span id="cb1-110"><a href="#cb1-110" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>Tariffs in the second Trump administration <span class="sc">\-</span> Wikipedia, accessed April 28, 2025, <span class="co">[</span><span class="ot">https://en.wikipedia.org/wiki/Tariffs\_in\_the\_second\_Trump\_administration</span><span class="co">](https://en.wikipedia.org/wiki/Tariffs_in_the_second_Trump_administration)</span>  </span>
<span id="cb1-111"><a href="#cb1-111" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>What Trump's global tariff announcement means for trade professionals, accessed April 28, 2025, <span class="co">[</span><span class="ot">https://tax.thomsonreuters.com/blog/what-trumps-global-tariff-announcement-means-for-trade-professionals/</span><span class="co">](https://tax.thomsonreuters.com/blog/what-trumps-global-tariff-announcement-means-for-trade-professionals/)</span>  </span>
<span id="cb1-112"><a href="#cb1-112" aria-hidden="true" tabindex="-1"></a><span class="ss">5. </span>See the full list of reciprocal tariffs by country from Trump's "Liberation Day" chart, accessed April 28, 2025, <span class="co">[</span><span class="ot">https://www.cbsnews.com/news/trump-reciprocal-tariffs-liberation-day-list/</span><span class="co">](https://www.cbsnews.com/news/trump-reciprocal-tariffs-liberation-day-list/)</span>  </span>
<span id="cb1-113"><a href="#cb1-113" aria-hidden="true" tabindex="-1"></a><span class="ss">6. </span>A timeline of Trump's tariff actions so far | PBS News, accessed April 28, 2025, <span class="co">[</span><span class="ot">https://www.pbs.org/newshour/economy/a-timeline-of-trumps-tariff-actions-so-far</span><span class="co">](https://www.pbs.org/newshour/economy/a-timeline-of-trumps-tariff-actions-so-far)</span>  </span>
<span id="cb1-114"><a href="#cb1-114" aria-hidden="true" tabindex="-1"></a><span class="ss">7. </span>Trump Tariffs: The Economic Impact of the Trump Trade War <span class="sc">\-</span> Tax Foundation, accessed April 28, 2025, <span class="co">[</span><span class="ot">https://taxfoundation.org/research/all/federal/trump-tariffs-trade-war/</span><span class="co">](https://taxfoundation.org/research/all/federal/trump-tariffs-trade-war/)</span>  </span>
<span id="cb1-115"><a href="#cb1-115" aria-hidden="true" tabindex="-1"></a><span class="ss">8. </span>Donald Trump announces 90-day tariff pause <span class="sc">\-</span> The Financial Express, accessed April 28, 2025, <span class="co">[</span><span class="ot">https://www.financialexpress.com/world-news/donald-trump-tariff-live-updates-china-india-us-asian-market-global-markets/3802671/</span><span class="co">](https://www.financialexpress.com/world-news/donald-trump-tariff-live-updates-china-india-us-asian-market-global-markets/3802671/)</span>  </span>
<span id="cb1-116"><a href="#cb1-116" aria-hidden="true" tabindex="-1"></a><span class="ss">9. </span>Trump announces 90-day pause on tariffs except on China <span class="sc">\-</span> Chinadaily.com.cn, accessed April 28, 2025, <span class="co">[</span><span class="ot">https://www.chinadaily.com.cn/a/202504/10/WS67f6b59ca3104d9fd381e6f6.html</span><span class="co">](https://www.chinadaily.com.cn/a/202504/10/WS67f6b59ca3104d9fd381e6f6.html)</span>  </span>
<span id="cb1-117"><a href="#cb1-117" aria-hidden="true" tabindex="-1"></a><span class="ss">10. </span>Trump hits back with a 125% tariff in escalating trade war with China <span class="sc">\-</span> AP News, accessed April 28, 2025, <span class="co">[</span><span class="ot">https://apnews.com/article/china-response-us-tariffs-104-d40d497f6e07ee4163d88443cb75ab3f</span><span class="co">](https://apnews.com/article/china-response-us-tariffs-104-d40d497f6e07ee4163d88443cb75ab3f)</span>  </span>
<span id="cb1-118"><a href="#cb1-118" aria-hidden="true" tabindex="-1"></a><span class="ss">11. </span>How to handle US-China tariffs and the end of de minimis <span class="sc">\-</span> Avalara, accessed April 28, 2025, <span class="co">[</span><span class="ot">https://www.avalara.com/blog/en/north-america/2025/02/how-to-handle-us-china-tariffs-de-minimis.html</span><span class="co">](https://www.avalara.com/blog/en/north-america/2025/02/how-to-handle-us-china-tariffs-de-minimis.html)</span>  </span>
<span id="cb1-119"><a href="#cb1-119" aria-hidden="true" tabindex="-1"></a><span class="ss">12. </span>US suspends President Trump's Reciprocal Tariff Policy for 90 days, except for China, accessed April 28, 2025, <span class="co">[</span><span class="ot">https://globaltaxnews.ey.com/news/2025-0868-us-suspends-president-trumps-reciprocal-tariff-policy-for-90-days-except-for-china</span><span class="co">](https://globaltaxnews.ey.com/news/2025-0868-us-suspends-president-trumps-reciprocal-tariff-policy-for-90-days-except-for-china)</span>  </span>
<span id="cb1-120"><a href="#cb1-120" aria-hidden="true" tabindex="-1"></a><span class="ss">13. </span>What's Happening With Trump Tariffs? New Rates and Trade Talks <span class="sc">\-</span> Kiplinger, accessed April 28, 2025, <span class="co">[</span><span class="ot">https://www.kiplinger.com/taxes/whats-happening-with-trump-tariffs</span><span class="co">](https://www.kiplinger.com/taxes/whats-happening-with-trump-tariffs)</span>  </span>
<span id="cb1-121"><a href="#cb1-121" aria-hidden="true" tabindex="-1"></a><span class="ss">14. </span>Trump tariff updates: US president unveils 90-day pause for most countries <span class="sc">\-</span> Al Jazeera, accessed April 28, 2025, <span class="co">[</span><span class="ot">https://www.aljazeera.com/news/liveblog/2025/4/9/trump-tariffs-stocks-dive-as-world-braces-for-duties-to-begin-at-midnight</span><span class="co">](https://www.aljazeera.com/news/liveblog/2025/4/9/trump-tariffs-stocks-dive-as-world-braces-for-duties-to-begin-at-midnight)</span>  </span>
<span id="cb1-122"><a href="#cb1-122" aria-hidden="true" tabindex="-1"></a><span class="ss">15. </span>Trump's Tariff-Related Trade Policy: Big Economic, Political Risks | China Digs In, accessed April 28, 2025, <span class="co">[</span><span class="ot">https://www.profarmer.com/news/policy-update/trumps-tariff-related-trade-policy-big-economic-political-risks-china-digs</span><span class="co">](https://www.profarmer.com/news/policy-update/trumps-tariff-related-trade-policy-big-economic-political-risks-china-digs)</span>  </span>
<span id="cb1-123"><a href="#cb1-123" aria-hidden="true" tabindex="-1"></a><span class="ss">16. </span>Trump limits tariffs on most nations for 90 days, raises taxes on Chinese imports <span class="sc">\-</span> AP News, accessed April 28, 2025, <span class="co">[</span><span class="ot">https://apnews.com/article/trump-tariffs-stock-market-china-recession-deals-e8e54a68397e6829e1d27552a1d7bfb9</span><span class="co">](https://apnews.com/article/trump-tariffs-stock-market-china-recession-deals-e8e54a68397e6829e1d27552a1d7bfb9)</span>  </span>
<span id="cb1-124"><a href="#cb1-124" aria-hidden="true" tabindex="-1"></a><span class="ss">17. </span>Trump tariffs updates: China hit with 145% duties as Wall Street slides <span class="sc">\-</span> Al Jazeera, accessed April 28, 2025, <span class="co">[</span><span class="ot">https://www.aljazeera.com/economy/liveblog/2025/4/10/trump-tariffs-live-stocks-skyrocket-as-many-duties-paused</span><span class="co">](https://www.aljazeera.com/economy/liveblog/2025/4/10/trump-tariffs-live-stocks-skyrocket-as-many-duties-paused)</span>  </span>
<span id="cb1-125"><a href="#cb1-125" aria-hidden="true" tabindex="-1"></a><span class="ss">18. </span>Amid Trump tariffs, China's trade and economy tsar steps into spotlight, accessed April 28, 2025, <span class="co">[</span><span class="ot">https://m.economictimes.com/news/international/business/amid-trump-tariffs-chinas-trade-and-economy-tsar-steps-into-spotlight/articleshow/120681528.cms?UTM\_Source=Google\_Newsstand\&amp;UTM\_Campaign=RSS\_Feed\&amp;UTM\_Medium=Referral</span><span class="co">](https://m.economictimes.com/news/international/business/amid-trump-tariffs-chinas-trade-and-economy-tsar-steps-into-spotlight/articleshow/120681528.cms?UTM_Source=Google_Newsstand&amp;UTM_Campaign=RSS_Feed&amp;UTM_Medium=Referral)</span>  </span>
<span id="cb1-126"><a href="#cb1-126" aria-hidden="true" tabindex="-1"></a><span class="ss">19. </span>Chinese firms race to open US factories as Trump's tariff war hits home <span class="sc">\-</span> Business Standard, accessed April 28, 2025, <span class="co">[</span><span class="ot">https://www.business-standard.com/world-news/china-manufacturers-move-us-factories-production-tariff-war-donald-trump-125042700109\_1.html</span><span class="co">](https://www.business-standard.com/world-news/china-manufacturers-move-us-factories-production-tariff-war-donald-trump-125042700109_1.html)</span>  </span>
<span id="cb1-127"><a href="#cb1-127" aria-hidden="true" tabindex="-1"></a><span class="ss">20. </span>US Treasury secretary says trade war with China is not 'sustainable' <span class="sc">\-</span> AP News, accessed April 28, 2025, <span class="co">[</span><span class="ot">https://apnews.com/article/tariffs-trade-taxes-trump-china-bessent-treasury-66668fa26957ece530a250fa8ea19faa</span><span class="co">](https://apnews.com/article/tariffs-trade-taxes-trump-china-bessent-treasury-66668fa26957ece530a250fa8ea19faa)</span>  </span>
<span id="cb1-128"><a href="#cb1-128" aria-hidden="true" tabindex="-1"></a><span class="ss">21. </span>China warns countries against making trade deals with the US unfavorable to Beijing <span class="sc">\-</span> AP News, accessed April 28, 2025, <span class="co">[</span><span class="ot">https://apnews.com/article/chian-us-tariffs-retaliation-18b3da9bed1aa1b3ee3a79e91c197730</span><span class="co">](https://apnews.com/article/chian-us-tariffs-retaliation-18b3da9bed1aa1b3ee3a79e91c197730)</span>  </span>
<span id="cb1-129"><a href="#cb1-129" aria-hidden="true" tabindex="-1"></a><span class="ss">22. </span>Fact Sheet: President Donald J. Trump Closes De Minimis Exemptions to Combat China's Role in America's Synthetic Opioid Crisis <span class="sc">\-</span> The White House, accessed April 28, 2025, <span class="co">[</span><span class="ot">https://www.whitehouse.gov/fact-sheets/2025/04/fact-sheet-president-donald-j-trump-closes-de-minimis-exemptions-to-combat-chinas-role-in-americas-synthetic-opioid-crisis/</span><span class="co">](https://www.whitehouse.gov/fact-sheets/2025/04/fact-sheet-president-donald-j-trump-closes-de-minimis-exemptions-to-combat-chinas-role-in-americas-synthetic-opioid-crisis/)</span>  </span>
<span id="cb1-130"><a href="#cb1-130" aria-hidden="true" tabindex="-1"></a><span class="ss">23. </span>Most Americans expect higher prices as a result of Trump's tariffs, a new AP-NORC poll finds <span class="sc">\-</span> AP News, accessed April 28, 2025, <span class="co">[</span><span class="ot">https://apnews.com/article/trump-economy-poll-tariffs-inflation-prices-recession-1d320115e8801e4970bd5cccf2742fc4</span><span class="co">](https://apnews.com/article/trump-economy-poll-tariffs-inflation-prices-recession-1d320115e8801e4970bd5cccf2742fc4)</span>  </span>
<span id="cb1-131"><a href="#cb1-131" aria-hidden="true" tabindex="-1"></a><span class="ss">24. </span>Bloomberg: Trump floats cutting China tariffs substantially in trade deal : r/stocks <span class="sc">\-</span> Reddit, accessed April 28, 2025, <span class="co">[</span><span class="ot">https://www.reddit.com/r/stocks/comments/1k5q7qb/bloomberg\_trump\_floats\_cutting\_china\_tariffs/</span><span class="co">](https://www.reddit.com/r/stocks/comments/1k5q7qb/bloomberg_trump_floats_cutting_china_tariffs/)</span>  </span>
<span id="cb1-132"><a href="#cb1-132" aria-hidden="true" tabindex="-1"></a><span class="ss">25. </span>Trump Wants China Concessions, Shein Hikes US Prices | Bloomberg: The Asia Trade 4/28/25 <span class="sc">\-</span> YouTube, accessed April 28, 2025, <span class="co">[</span><span class="ot">https://www.youtube.com/watch?v=xjOHWzDNkxs</span><span class="co">](https://www.youtube.com/watch?v=xjOHWzDNkxs)</span>  </span>
<span id="cb1-133"><a href="#cb1-133" aria-hidden="true" tabindex="-1"></a><span class="ss">26. </span>U.S. Tariffs Update – April 14, 2025 <span class="sc">\-</span> Fredrikson &amp; Byron P.A., accessed April 28, 2025, <span class="co">[</span><span class="ot">https://www.fredlaw.com/alert-u-s-tariffs-update-april-14-2025</span><span class="co">](https://www.fredlaw.com/alert-u-s-tariffs-update-april-14-2025)</span>  </span>
<span id="cb1-134"><a href="#cb1-134" aria-hidden="true" tabindex="-1"></a><span class="ss">27. </span>Trump threatens more tariffs on China as global markets shudder <span class="sc">\-</span> AP News, accessed April 28, 2025, <span class="co">[</span><span class="ot">https://apnews.com/article/trump-tariffs-stock-market-52a00ea2bb92a067ee72343941b02cd4</span><span class="co">](https://apnews.com/article/trump-tariffs-stock-market-52a00ea2bb92a067ee72343941b02cd4)</span>  </span>
<span id="cb1-135"><a href="#cb1-135" aria-hidden="true" tabindex="-1"></a><span class="ss">28. </span>Experts warn Trump's trade war with China could erupt into a cold ..., accessed April 28, 2025, <span class="co">[</span><span class="ot">https://www.independent.co.uk/news/world/americas/us-politics/trump-china-tariffs-cold-war-b2736957.html</span><span class="co">](https://www.independent.co.uk/news/world/americas/us-politics/trump-china-tariffs-cold-war-b2736957.html)</span>  </span>
<span id="cb1-136"><a href="#cb1-136" aria-hidden="true" tabindex="-1"></a><span class="ss">29. </span>'Not seeking trade imbalance': China releases white paper on trade ..., accessed April 28, 2025, <span class="co">[</span><span class="ot">https://www.business-standard.com/world-news/china-us-trade-white-paper-2025-tariffs-dispute-phase-one-125040900941\_1.html</span><span class="co">](https://www.business-standard.com/world-news/china-us-trade-white-paper-2025-tariffs-dispute-phase-one-125040900941_1.html)</span>  </span>
<span id="cb1-137"><a href="#cb1-137" aria-hidden="true" tabindex="-1"></a><span class="ss">30. </span>'Unilateralist and protectionist acts': 10 key points from China's White ..., accessed April 28, 2025, <span class="co">[</span><span class="ot">https://timesofindia.indiatimes.com/world/china/unilateralist-and-protectionist-acts-10-key-points-from-chinas-white-paper-on-trumps-tariff/articleshow/120123443.cms</span><span class="co">](https://timesofindia.indiatimes.com/world/china/unilateralist-and-protectionist-acts-10-key-points-from-chinas-white-paper-on-trumps-tariff/articleshow/120123443.cms)</span>  </span>
<span id="cb1-138"><a href="#cb1-138" aria-hidden="true" tabindex="-1"></a><span class="ss">31. </span>China issues white paper outlining stance on economic ties with ..., accessed April 28, 2025, <span class="co">[</span><span class="ot">https://news.cgtn.com/news/2025-04-09/China-issues-white-paper-outlining-stance-on-economic-ties-with-U-S--1CqH8oO3BSg/p.html</span><span class="co">](https://news.cgtn.com/news/2025-04-09/China-issues-white-paper-outlining-stance-on-economic-ties-with-U-S--1CqH8oO3BSg/p.html)</span>  </span>
<span id="cb1-139"><a href="#cb1-139" aria-hidden="true" tabindex="-1"></a><span class="ss">32. </span>China's State Council Releases White Paper "China's Position on Certain Issues in China-US Economic and Trade Relations" <span class="sc">\-</span> China Continuously Improves IP Protection and Prohibits Forced Technology Transfer <span class="sc">\-</span> China IP Law Update, accessed April 28, 2025, <span class="co">[</span><span class="ot">https://www.chinaiplawupdate.com/2025/04/chinas-state-council-releases-white-paper-chinas-position-on-certain-issues-in-china-us-economic-and-trade-relations-china-continuously-improves-ip-protection-and-prohibits-forced-technology/</span><span class="co">](https://www.chinaiplawupdate.com/2025/04/chinas-state-council-releases-white-paper-chinas-position-on-certain-issues-in-china-us-economic-and-trade-relations-china-continuously-improves-ip-protection-and-prohibits-forced-technology/)</span>  </span>
<span id="cb1-140"><a href="#cb1-140" aria-hidden="true" tabindex="-1"></a><span class="ss">33. </span>China releases white paper on China-US economic, trade relations ..., accessed April 28, 2025, <span class="co">[</span><span class="ot">http://english.scio.gov.cn/m/whitepapers/2025-04/09/content\_117814327.html</span><span class="co">](http://english.scio.gov.cn/m/whitepapers/2025-04/09/content_117814327.html)</span>  </span>
<span id="cb1-141"><a href="#cb1-141" aria-hidden="true" tabindex="-1"></a><span class="ss">34. </span>Full text: China's Position on Some Issues Concerning China-US Economic and Trade Relations | english.scio.gov.cn, accessed April 28, 2025, <span class="co">[</span><span class="ot">http://english.scio.gov.cn/whitepapers/2025-04/09/content\_117814362.html</span><span class="co">](http://english.scio.gov.cn/whitepapers/2025-04/09/content_117814362.html)</span>  </span>
<span id="cb1-142"><a href="#cb1-142" aria-hidden="true" tabindex="-1"></a><span class="ss">35. </span>China releases white paper on China-U.S. economic, trade relations <span class="sc">\-</span> Xinhua, accessed April 28, 2025, <span class="co">[</span><span class="ot">https://english.news.cn/20250409/7458b316f22944fe9059d229d4d22ed3/c.html</span><span class="co">](https://english.news.cn/20250409/7458b316f22944fe9059d229d4d22ed3/c.html)</span>  </span>
<span id="cb1-143"><a href="#cb1-143" aria-hidden="true" tabindex="-1"></a><span class="ss">36. </span>China releases white paper on China-US economic, trade relations <span class="sc">\-</span> Chinadaily.com.cn, accessed April 28, 2025, <span class="co">[</span><span class="ot">https://www.chinadaily.com.cn/a/202504/09/WS67f61b3fa3104d9fd381e5cf.html</span><span class="co">](https://www.chinadaily.com.cn/a/202504/09/WS67f61b3fa3104d9fd381e5cf.html)</span>  </span>
<span id="cb1-144"><a href="#cb1-144" aria-hidden="true" tabindex="-1"></a><span class="ss">37. </span>Full text: China's Position on Some Issues Concerning China-US Economic, Trade Relations, accessed April 28, 2025, <span class="co">[</span><span class="ot">https://www.globaltimes.cn/page/202504/1331740.shtml</span><span class="co">](https://www.globaltimes.cn/page/202504/1331740.shtml)</span>  </span>
<span id="cb1-145"><a href="#cb1-145" aria-hidden="true" tabindex="-1"></a><span class="ss">38. </span>China waives tariffs on some US goods, but denies Trump's claim that talks are under way, accessed April 28, 2025, <span class="co">[</span><span class="ot">https://www.straitstimes.com/asia/east-asia/china-waives-tariffs-on-some-us-goods-but-denies-trumps-claim-that-talks-are-underway</span><span class="co">](https://www.straitstimes.com/asia/east-asia/china-waives-tariffs-on-some-us-goods-but-denies-trumps-claim-that-talks-are-underway)</span>  </span>
<span id="cb1-146"><a href="#cb1-146" aria-hidden="true" tabindex="-1"></a><span class="ss">39. </span>China's latest response on tariffs sends the market reeling <span class="sc">\-</span> TheStreet, accessed April 28, 2025, <span class="co">[</span><span class="ot">https://www.thestreet.com/crypto/policy/chinas-latest-response-on-tariffs-sends-shock-into-the-market</span><span class="co">](https://www.thestreet.com/crypto/policy/chinas-latest-response-on-tariffs-sends-shock-into-the-market)</span>  </span>
<span id="cb1-147"><a href="#cb1-147" aria-hidden="true" tabindex="-1"></a><span class="ss">40. </span>US-China Tariff War Escalates | Global Trade War | Xi Jinping | N18G <span class="sc">\-</span> YouTube, accessed April 28, 2025, <span class="co">[</span><span class="ot">https://www.youtube.com/watch?v=PH0TtM7405o</span><span class="co">](https://www.youtube.com/watch?v=PH0TtM7405o)</span>  </span>
<span id="cb1-148"><a href="#cb1-148" aria-hidden="true" tabindex="-1"></a><span class="ss">41. </span>Wall Street Journal says China called Trump's bluff, wins this round of tariff war but the good news is... <span class="sc">\-</span> The Times of India, accessed April 28, 2025, <span class="co">[</span><span class="ot">https://timesofindia.indiatimes.com/world/us/wall-street-journal-says-china-called-trumps-bluff-wins-this-round-but-the-good-news-is-/articleshow/120591261.cms</span><span class="co">](https://timesofindia.indiatimes.com/world/us/wall-street-journal-says-china-called-trumps-bluff-wins-this-round-but-the-good-news-is-/articleshow/120591261.cms)</span>  </span>
<span id="cb1-149"><a href="#cb1-149" aria-hidden="true" tabindex="-1"></a><span class="ss">42. </span>Trump tariffs: President vents at China over Boeing as Beijing denies claims of trade deal talks | The Independent, accessed April 28, 2025, <span class="co">[</span><span class="ot">https://www.independent.co.uk/news/world/americas/us-politics/trump-tariffs-china-live-updates-auto-recession-b2738585.html</span><span class="co">](https://www.independent.co.uk/news/world/americas/us-politics/trump-tariffs-china-live-updates-auto-recession-b2738585.html)</span>  </span>
<span id="cb1-150"><a href="#cb1-150" aria-hidden="true" tabindex="-1"></a><span class="ss">43. </span>President Trump says U.S. met this morning with China, declines to identify individuals involved <span class="sc">\-</span> YouTube, accessed April 28, 2025, <span class="co">[</span><span class="ot">https://www.youtube.com/watch?v=o\_wHHVnBhgE</span><span class="co">](https://www.youtube.com/watch?v=o_wHHVnBhgE)</span>  </span>
<span id="cb1-151"><a href="#cb1-151" aria-hidden="true" tabindex="-1"></a><span class="ss">44. </span>China considers exempting some goods from US tariffs <span class="sc">\-</span> Eric Cotter ..., accessed April 28, 2025, <span class="co">[</span><span class="ot">https://cotteraccounting.com/2025/04/25/china-considers-exempting-some-goods-from-us-tariffs/</span><span class="co">](https://cotteraccounting.com/2025/04/25/china-considers-exempting-some-goods-from-us-tariffs/)</span>  </span>
<span id="cb1-152"><a href="#cb1-152" aria-hidden="true" tabindex="-1"></a><span class="ss">45. </span>China mulling US tariff exemptions <span class="sc">\-</span> Taipei Times, accessed April 28, 2025, <span class="co">[</span><span class="ot">https://www.taipeitimes.com/News/biz/archives/2025/04/26/2003835824</span><span class="co">](https://www.taipeitimes.com/News/biz/archives/2025/04/26/2003835824)</span>  </span>
<span id="cb1-153"><a href="#cb1-153" aria-hidden="true" tabindex="-1"></a><span class="ss">46. </span>China considers exempting some goods from US tariffs <span class="sc">\-</span> The Standard, accessed April 28, 2025, <span class="co">[</span><span class="ot">https://www.thestandard.com.hk/china-news/article/301176/China-considers-exempting-some-goods-from-US-tariffs</span><span class="co">](https://www.thestandard.com.hk/china-news/article/301176/China-considers-exempting-some-goods-from-US-tariffs)</span>  </span>
<span id="cb1-154"><a href="#cb1-154" aria-hidden="true" tabindex="-1"></a><span class="ss">47. </span>China May Exempt Some US Goods From Tariffs as Costs Rise : r/StockMarket <span class="sc">\-</span> Reddit, accessed April 28, 2025, <span class="co">[</span><span class="ot">https://www.reddit.com/r/StockMarket/comments/1k7jjwz/china\_may\_exempt\_some\_us\_goods\_from\_tariffs\_as/</span><span class="co">](https://www.reddit.com/r/StockMarket/comments/1k7jjwz/china_may_exempt_some_us_goods_from_tariffs_as/)</span>  </span>
<span id="cb1-155"><a href="#cb1-155" aria-hidden="true" tabindex="-1"></a><span class="ss">48. </span>Tariff uncertainty: Impacts on markets and portfolios <span class="sc">\-</span> BlackRock, accessed April 28, 2025, <span class="co">[</span><span class="ot">https://www.blackrock.com/us/financial-professionals/insights/tariffs-and-investment-portfolios</span><span class="co">](https://www.blackrock.com/us/financial-professionals/insights/tariffs-and-investment-portfolios)</span>  </span>
<span id="cb1-156"><a href="#cb1-156" aria-hidden="true" tabindex="-1"></a><span class="ss">49. </span>Wall Street falls again as losses wipe out all post-election gains for the S<span class="sc">\&amp;</span>P 500 | AP News, accessed April 28, 2025, <span class="co">[</span><span class="ot">https://apnews.com/article/stocks-markets-rates-tariffs-trump-1ca865fa6abcca716b5e7c9281ea6e07</span><span class="co">](https://apnews.com/article/stocks-markets-rates-tariffs-trump-1ca865fa6abcca716b5e7c9281ea6e07)</span>  </span>
<span id="cb1-157"><a href="#cb1-157" aria-hidden="true" tabindex="-1"></a><span class="ss">50. </span>Taking Trump's Tariffs Seriously: The Fiscal and Economic Impact for NYC, accessed April 28, 2025, <span class="co">[</span><span class="ot">https://comptroller.nyc.gov/reports/taking-trumps-tariffs-seriously-the-fiscal-and-economic-impact-for-nyc/</span><span class="co">](https://comptroller.nyc.gov/reports/taking-trumps-tariffs-seriously-the-fiscal-and-economic-impact-for-nyc/)</span>  </span>
<span id="cb1-158"><a href="#cb1-158" aria-hidden="true" tabindex="-1"></a><span class="ss">51. </span>Trump threatens to impose an additional 50% tariff on China <span class="sc">\-</span> CBS News, accessed April 28, 2025, <span class="co">[</span><span class="ot">https://www.cbsnews.com/news/trump-tariffs-china-50-percent-tariff-retaliatory/</span><span class="co">](https://www.cbsnews.com/news/trump-tariffs-china-50-percent-tariff-retaliatory/)</span>  </span>
<span id="cb1-159"><a href="#cb1-159" aria-hidden="true" tabindex="-1"></a><span class="ss">52. </span>China learned from Trump's first trade war and changed its tactics when tariffs came again, accessed April 28, 2025, <span class="co">[</span><span class="ot">https://www.bnnbloomberg.ca/business/international/2025/03/09/china-learned-from-trumps-first-trade-war-and-changed-its-tactics-when-tariffs-came-again/</span><span class="co">](https://www.bnnbloomberg.ca/business/international/2025/03/09/china-learned-from-trumps-first-trade-war-and-changed-its-tactics-when-tariffs-came-again/)</span>  </span>
<span id="cb1-160"><a href="#cb1-160" aria-hidden="true" tabindex="-1"></a><span class="ss">53. </span>China Responds To Donald Trump's Tariff Backflip | 10 News First <span class="sc">\-</span> YouTube, accessed April 28, 2025, <span class="co">[</span><span class="ot">https://www.youtube.com/watch?v=AcwdqisUODw</span><span class="co">](https://www.youtube.com/watch?v=AcwdqisUODw)</span>  </span>
<span id="cb1-161"><a href="#cb1-161" aria-hidden="true" tabindex="-1"></a><span class="ss">54. </span>US-China tariff tensions are not just a trade spat, expert says <span class="sc">\-</span> YouTube, accessed April 28, 2025, <span class="co">[</span><span class="ot">https://www.youtube.com/watch?v=ZLlV26EldEE</span><span class="co">](https://www.youtube.com/watch?v=ZLlV26EldEE)</span>  </span>
<span id="cb1-162"><a href="#cb1-162" aria-hidden="true" tabindex="-1"></a><span class="ss">55. </span>US and global economic outlook deteriorates in Trump trade war ..., accessed April 28, 2025, <span class="co">[</span><span class="ot">https://apnews.com/article/recession-imf-economy-tariffs-5ec37492c9fac499923c094776b87552</span><span class="co">](https://apnews.com/article/recession-imf-economy-tariffs-5ec37492c9fac499923c094776b87552)</span>  </span>
<span id="cb1-163"><a href="#cb1-163" aria-hidden="true" tabindex="-1"></a><span class="ss">56. </span>Tariffs &amp; trade war: Market commentary | Robeco Global, accessed April 28, 2025, <span class="co">[</span><span class="ot">https://www.robeco.com/en-int/insights/2025/04/tariffs-trade-war-market-commentary</span><span class="co">](https://www.robeco.com/en-int/insights/2025/04/tariffs-trade-war-market-commentary)</span>  </span>
<span id="cb1-164"><a href="#cb1-164" aria-hidden="true" tabindex="-1"></a><span class="ss">57. </span>China and the Impact of “Liberation Day” Tariffs <span class="sc">\-</span> CSIS, accessed April 28, 2025, <span class="co">[</span><span class="ot">https://www.csis.org/analysis/china-and-impact-liberation-day-tariffs</span><span class="co">](https://www.csis.org/analysis/china-and-impact-liberation-day-tariffs)</span>  </span>
<span id="cb1-165"><a href="#cb1-165" aria-hidden="true" tabindex="-1"></a><span class="ss">58. </span>Trump's Trade War is a Major Economic and Strategic Blunder, accessed April 28, 2025, <span class="co">[</span><span class="ot">https://www.americanprogress.org/article/trumps-trade-war-is-a-major-economic-and-strategic-blunder/</span><span class="co">](https://www.americanprogress.org/article/trumps-trade-war-is-a-major-economic-and-strategic-blunder/)</span>  </span>
<span id="cb1-166"><a href="#cb1-166" aria-hidden="true" tabindex="-1"></a><span class="ss">59. </span>Trump-China trade war: Which US companies could be worst hit ..., accessed April 28, 2025, <span class="co">[</span><span class="ot">https://www.aljazeera.com/news/2025/4/15/trump-china-trade-war-which-us-companies-could-be-worst-hit</span><span class="co">](https://www.aljazeera.com/news/2025/4/15/trump-china-trade-war-which-us-companies-could-be-worst-hit)</span>  </span>
<span id="cb1-167"><a href="#cb1-167" aria-hidden="true" tabindex="-1"></a><span class="ss">60. </span>PIIE experts react to Trump's tariffs announced April 2, accessed April 28, 2025, <span class="co">[</span><span class="ot">https://www.piie.com/blogs/realtime-economics/2025/piie-experts-react-trumps-tariffs-announced-april-2</span><span class="co">](https://www.piie.com/blogs/realtime-economics/2025/piie-experts-react-trumps-tariffs-announced-april-2)</span>  </span>
<span id="cb1-168"><a href="#cb1-168" aria-hidden="true" tabindex="-1"></a><span class="ss">61. </span>What Trump's Trade War Would Mean, in Nine Charts <span class="sc">\-</span> Council on Foreign Relations, accessed April 28, 2025, <span class="co">[</span><span class="ot">https://www.cfr.org/article/what-trumps-trade-war-would-mean-nine-charts</span><span class="co">](https://www.cfr.org/article/what-trumps-trade-war-would-mean-nine-charts)</span>  </span>
<span id="cb1-169"><a href="#cb1-169" aria-hidden="true" tabindex="-1"></a><span class="ss">62. </span>Xi Aims to Mend Ties With Europe as Trump Alienates Trading Partners <span class="sc">\-</span> YouTube, accessed April 28, 2025, <span class="co">[</span><span class="ot">https://www.youtube.com/watch?v=4i5jL5xK9Cg</span><span class="co">](https://www.youtube.com/watch?v=4i5jL5xK9Cg)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2026 Oleksandr Shepotylo</p>
</div>   
    <div class="nav-footer-center">
<p>shepotylo@gmail.com</p>
</div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/oshepotylo">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/oleksandr-shepotylo-b050353/">
      <i class="bi bi-linkedin" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item">
    <a class="nav-link" href="https://oleksandrshepotylo.substack.com/">
<p><iconify-icon role="img" inline="" icon="simple-icons:substack" aria-label="Icon substack from simple-icons Iconify.design set." title="Icon substack from simple-icons Iconify.design set."></iconify-icon></p>
</a>
  </li>  
    <li class="nav-item">
    <a class="nav-link" href="https://orcid.org/0000-0003-4990-6025">
<p><iconify-icon role="img" inline="" icon="academicons:orcid" aria-label="Icon orcid from academicons Iconify.design set." title="Icon orcid from academicons Iconify.design set."></iconify-icon></p>
</a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>