---
title: "Trump Trade War Diary — April 17, 2025"
description: "The White House launched Restoring America's maritime dominance initiative with a publication at the White House website. The initiative aims at strenghening the US commercial shipbuilding capacity and maritime workforce."
date: "2025-04-17"
categories: [trade-wars, trump-trade-war-diary]
---

The White House launched Restoring America's maritime dominance initiative with a [publication](https://www.whitehouse.gov/presidential-actions/2025/04/restoring-americas-maritime-dominance/) at the White House website. The initiative aims at strenghening the US commercial shipbuilding capacity and maritime workforce. It claims that US currently construct less than 1% of the world's commercial ships, while China has about 50%. In addition to the measures directed to increasing financing and investment of US shipbuilding, it will introduce new Harbor Maintenance Fees and Other charges. Also, it plans to engage Allies and Partners.

USTR prepared the Section 301 Action on China, available at [USTR website](https://ustr.gov/about/policy-offices/press-office/press-releases/2025/april/ustr-section-301-action-chinas-targeting-maritime-logistics-and-shipbuilding-sectors-dominance). The document outlines the US position on the trade war with China, including the imposition of tariffs and other trade restrictions. It emphasizes the need for a comprehensive approach to address China's trade practices and calls for continued engagement with allies to counter China's economic influence.

The timeline of the proposed measures are: "For the first 180 days the applicable fees will be set at $0.

(1) In the first phase, after 180 days:

Fees on vessel owners and operators of China based on net tonnage per U.S. voyage, increasing incrementally over the following years;
Fees on operators of Chinese-built ships based on net tonnage or containers, increasing incrementally over the following years; and
To incentivize U.S.-built car carrier vessels, fees on foreign-built car carrier vessels based on their capacity.
(2) The second phase actions will not take place for 3 years:

To incentivize U.S.-built liquified natural gas (LNG) vessels, limited restrictions on transporting LNG via foreign vessels. These restrictions will increase incrementally over 22 years."
